import {useEffect,useState} from 'react';
import type {FormEvent} from 'react';
import {api} from './api';

type Account={id:number;email:string;verified:boolean;is_admin:boolean;created_at:number;last_login:number;banned:boolean;banned_until:number;ban_reason:string;admin_note:string;identity_count:number;session_count:number;connections:number};
type Detail=Account&{identities:{name:string;uid:string;is_default:boolean}[];audit:{action:string;detail:string;actor:string;created_at:number}[]};
type Page={accounts:Account[];total:number;page:number;page_size:number;stats:{total:number;verified:number;banned:number;admins:number;sessions:number}};
const actions:Record<string,string>={ban:'封禁',unban:'解封',revoke:'强制退出',role:'修改管理员角色',note:'保存管理备注'};
const date=(n:number)=>n>0?new Date(n*1000).toLocaleString('zh-CN'):'尚无记录';
const auditDetail=(text:string)=>text.replace(/；到期：(-?\d+)$/,(_,value)=>Number(value)===-1?'；永久封禁':'；封禁至 '+date(Number(value)));
const status=(a:Account)=>a.banned?'已封禁':a.verified?'正常':'待验证';
export function AdminAccounts({currentEmail}:{currentEmail:string}){
  const[search,setSearch]=useState(''),[filter,setFilter]=useState(''),[page,setPage]=useState(0),[data,setData]=useState<Page|null>(null),[detail,setDetail]=useState<Detail|null>(null),[message,setMessage]=useState(''),[busy,setBusy]=useState(false),[loading,setLoading]=useState(false);
  const[action,setAction]=useState(''),[text,setText]=useState(''),[seconds,setSeconds]=useState('0'),[password,setPassword]=useState('');
  const[query,setQuery]=useState({search:'',status:'',page:0}),[revision,setRevision]=useState(0);
  useEffect(()=>{let active=true;setLoading(true);api<Page>(`/admin/accounts?${new URLSearchParams({search:query.search,status:query.status,page:String(query.page)})}`).then(d=>{if(active)setData(d);}).catch(e=>{if(active)setMessage(e.message);}).finally(()=>{if(active)setLoading(false);});return()=>{active=false;};},[query,revision]);
  async function inspect(id:number){setMessage('');setDetail(null);setAction('');setPassword('');setBusy(true);try{setDetail(await api<Detail>(`/admin/accounts/${id}`));}catch(e){setMessage(e instanceof Error?e.message:'读取失败');}finally{setBusy(false);}}
  function choose(value:string){setAction(value);setPassword('');setText(value==='note'?detail?.admin_note??'':'');setSeconds('0');setMessage('');}
  async function submit(e:FormEvent){e.preventDefault();if(!detail||!action)return;setBusy(true);setMessage('');try{const result=await api<{message:string}>(`/admin/accounts/${detail.id}`,{password,action,text,seconds:Number(seconds),is_admin:!detail.is_admin});setMessage(result.message);setAction('');setRevision(v=>v+1);setDetail(await api<Detail>(`/admin/accounts/${detail.id}`));}catch(e){setMessage(e instanceof Error?e.message:'操作失败');}finally{setPassword('');setBusy(false);}}
  function listPage(next:number){setPage(next);setQuery({search:query.search,status:query.status,page:next});}
  return <section className="admin-accounts">
    <p className="muted">管理网站账号与登录。封禁立即断开该账号所有网页连接，保留原身份；不会修改 TS 服务器封禁或身份权限。</p>
    {message&&<p role="status" className="auth-help">{message}</p>}
    {data&&<div className="account-stats">{[['账号',data.stats.total],['已验证',data.stats.verified],['封禁',data.stats.banned],['管理员',data.stats.admins],['有效会话',data.stats.sessions]].map(([label,n])=><div key={label}><strong>{n}</strong><small>{label}</small></div>)}</div>}
    <form className="account-search" onSubmit={e=>{e.preventDefault();setPage(0);setQuery({search,status:filter,page:0});setDetail(null);}}><label>邮箱搜索<input value={search} maxLength={254} onChange={e=>setSearch(e.target.value)} placeholder="按邮箱部分内容查询"/></label><label>账号状态<select value={filter} onChange={e=>setFilter(e.target.value)}><option value="">全部账号</option><option value="active">正常</option><option value="pending">待验证</option><option value="banned">封禁</option><option value="admin">管理员</option></select></label><button className="secondary" disabled={loading||busy}>查询</button><button type="button" className="secondary" disabled={loading||busy} onClick={()=>setRevision(v=>v+1)}>刷新</button></form>
    <p className="muted" role="status">{loading?'正在读取账号…':`共 ${data?.total??0} 个结果 · 第 ${page+1} 页`}</p>
    <div className="account-list">{!loading&&data?.accounts.map(a=><button type="button" disabled={busy} key={a.id} className={`account-row ${detail?.id===a.id?'selected':''}`} onClick={()=>inspect(a.id)}><span><strong>{a.email}</strong><small>#{a.id} · {a.is_admin?'管理员':'普通账号'} · {status(a)}</small></span><span><small>{a.identity_count} 身份 · {a.session_count} 会话 · {a.connections} 连接</small><small>最近登录：{date(a.last_login)}</small></span></button>)}{!loading&&data?.total===0&&<p className="muted">没有匹配的账号。</p>}</div>
    <div className="split-actions"><button className="secondary" disabled={page===0||loading||busy} onClick={()=>listPage(page-1)}>上一页</button><button className="secondary" disabled={!data||(page+1)*50>=data.total||loading||busy} onClick={()=>listPage(page+1)}>下一页</button></div>
    {detail&&<section className="account-detail"><h3>{detail.email}</h3><dl><dt>账号 ID / 状态</dt><dd>#{detail.id} · {status(detail)} · {detail.is_admin?'管理员':'普通账号'}</dd><dt>注册时间</dt><dd>{date(detail.created_at)}</dd><dt>最后登录</dt><dd>{date(detail.last_login)}</dd><dt>封禁期限</dt><dd>{detail.banned_until===-1?'永久':detail.banned_until>0?date(detail.banned_until):'未封禁'}</dd><dt>封禁原因</dt><dd>{detail.ban_reason||'—'}</dd><dt>管理备注</dt><dd>{detail.admin_note||'—'}</dd></dl>
      <div className="split-actions"><button className="secondary danger" disabled={busy||detail.email===currentEmail} onClick={()=>choose(detail.banned?'unban':'ban')}>{detail.banned?'解封账号':'封禁账号'}</button><button className="secondary" disabled={busy||detail.email===currentEmail} onClick={()=>choose('revoke')}>退出全部设备</button><button className="secondary" disabled={busy||detail.email===currentEmail||!detail.verified||detail.banned} onClick={()=>choose('role')}>{detail.is_admin?'取消管理员':'设为管理员'}</button><button className="secondary" disabled={busy} onClick={()=>choose('note')}>编辑备注</button></div>
      {action&&<form className="account-action" onSubmit={submit}><h4>{actions[action]}</h4><p className="muted">目标：{detail.email}{action==='role'?'。角色变更会撤销旧登录，重新登录后生效。':action==='ban'?'。旧会话撤销，解封后须重新登录，身份保留。':''}</p><fieldset disabled={busy}>{action==='ban'&&<label>封禁时长<select value={seconds} onChange={e=>setSeconds(e.target.value)}><option value="0">永久</option><option value="3600">1 小时</option><option value="86400">1 天</option><option value="604800">7 天</option><option value="2592000">30 天</option></select></label>}{action!=='role'&&<label>{action==='note'?'内部管理备注':'操作原因'}<textarea value={text} onChange={e=>setText(e.target.value)} maxLength={500} required={action==='ban'}/></label>}<label>复核当前管理员密码<input type="password" autoComplete="current-password" value={password} onChange={e=>setPassword(e.target.value)} required maxLength={128}/></label><div className="split-actions"><button className="primary">{busy?'正在处理…':`确认${actions[action]}`}</button><button type="button" className="secondary" onClick={()=>{setAction('');setPassword('');}}>取消</button></div></fieldset></form>}
      <h4>绑定身份（{detail.identity_count}）</h4><small className="muted">仅展示名称和 UID，最多100条，不提供私钥或身份导出。</small>{detail.identities.map(i=><p key={i.uid} className="account-identity"><strong>{i.name}{i.is_default?' · 默认':''}</strong><code>{i.uid}</code></p>)}
      <h4>最近管理操作</h4>{detail.audit.length===0?<p className="muted">暂无操作记录。</p>:detail.audit.map((a,i)=><article className="audit-row" key={i}><strong>{actions[a.action]??a.action}</strong><small>{date(a.created_at)} · {a.actor}</small><p>{auditDetail(a.detail)||'—'}</p></article>)}
    </section>}
  </section>;
}
