import {useEffect,useRef,useState} from 'react';
import {api} from './api';
import {useAccountPreference} from './account-preferences';
import {usePrivateScreen} from './private-screen';
import {OrdinaryChat} from './OrdinaryChat';
import type {OrdinaryPending} from './OrdinaryChat';
import type {FriendLocation} from './friend-presence';
import {ImageCropper} from './ImageCropper';
import {Sticker,StickerPicker} from './Stickers';
import {applyReadReceipt,burnDurations,validEnvelope,checkPrekey,createAutomaticIdentity,createIdentity,cryptoModule,exportIdentity,loadLocal,openMessage,persist,rememberDevice,safetyCode,saveImportedIdentity,saveLocal,sealMessage,unlockState} from './friend-crypto';
import type {Encrypted,Envelope,Unlocked} from './friend-crypto';
import {friendEvents} from './friend-notifications';
import type {FriendEvent,FriendSnapshot} from './friend-notifications';
import type {Profile} from './ProfileSettings';
type Me={id:number;code:string;public_key:string;storage_enabled:boolean;retention_days:number;prekeys_left:number;share_presence:boolean};
type Friend={online?:boolean;locations?:FriendLocation[];id:number;name:string;about?:string;avatar_hash?:string;public_key:string;device:string;requester:number;status:number;blocked_by:number;allow_server?:boolean;peer_allow_server?:boolean;mode_epoch?:number};
type Message={seq:number;id:string;sender:number;recipient:number;created_at:number;expires:number;burn:boolean;burn_seconds?:number|null;read_at:number|null;mode?:'e2ee'|'server';epoch?:number};
type Display=Message&{value?:Envelope;error?:string;burnAt?:number};
const title=(friend:Friend)=>friend.name||`WebTS 用户 ${friend.id}`;
function FriendAvatar({friend}:{friend:Friend}){
  const[failed,setFailed]=useState(''),[attempt,setAttempt]=useState(0);const hash=friend.avatar_hash;
  useEffect(()=>{setFailed('');setAttempt(0);},[hash]);
  useEffect(()=>{if(!hash||failed!==hash||attempt>=2)return;const timer=setTimeout(()=>{setAttempt(v=>v+1);setFailed('');},1500*(attempt+1));return()=>clearTimeout(timer);},[failed,hash,attempt]);
  return <span className="avatar">{hash&&/^[a-f0-9]{64}$/.test(hash)&&failed!==hash?<img src={`/api/friends/${friend.id}/avatar?v=${hash}&retry=${attempt}`} loading="lazy" alt="" onError={()=>setFailed(hash)}/>:Array.from(title(friend))[0]}</span>;
}
async function privateApi<T>(state:Unlocked,path:string,body?:unknown):Promise<T>{
  const r=await fetch(`/api/friends${path}`,{method:body===undefined?'GET':'POST',credentials:'same-origin',headers:{'x-webts-chat-device':state.saved.lease,...(body===undefined?{}:{'content-type':'application/json'})},body:body===undefined?undefined:JSON.stringify(body)});
  if(!r.ok){const data=await r.json().catch(()=>null);throw Object.assign(new Error(data?.error??'加密私信请求失败'),{status:r.status});}return r.json();
}
function download(record:Encrypted){const url=URL.createObjectURL(new Blob([JSON.stringify(record)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download=`webts-private-identity-${record.account}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
export function Friends({open,inline,compact=false,display='floating',changeDisplay,profile,close,onUnread,onNew,onJoin}:{open:boolean;inline:boolean;compact?:boolean;display?:'floating'|'docked';changeDisplay?:(mode:'floating'|'docked')=>void;profile?:Profile;onJoin:(peer:number,location:FriendLocation)=>Promise<void>;close:()=>void;onUnread:(count:number)=>void;onNew:(event:FriendEvent)=>void}){
  const[me,setMe]=useState<Me>(),[friends,setFriends]=useState<Friend[]>([]),[selected,setSelected]=useState<number>(),[records,setRecords]=useState<Display[]>([]),[draft,setDraft]=useState(''),[image,setImage]=useState(''),[crop,setCrop]=useState<File>(),[burn,setBurn]=useAccountPreference('burn',false),[burnSeconds,setBurnSeconds]=useAccountPreference('burnSeconds',60),[status,setStatus]=useState(''),[busy,setBusy]=useState(false),[passphrase,setPassphrase]=useState(''),[confirm,setConfirm]=useState(''),[password,setPassword]=useState(''),[backup,setBackup]=useState<Encrypted>(),[unlocked,setUnlocked]=useState(false),[code,setCode]=useState(''),[safety,setSafety]=useState(''),[trusted,setTrusted]=useState(false),[confirmTrust,setConfirmTrust]=useState(false),[before,setBefore]=useState(0),[showKeys,setShowKeys]=useState(false),[automatic,setAutomatic]=useState(true);
  const engine=useRef<Unlocked|undefined>(undefined),dialog=useRef<HTMLDialogElement>(null),localRelease=useRef<(()=>void)|undefined>(undefined),operation=useRef(false),alive=useRef(true),snapshot=useRef<FriendSnapshot|undefined>(undefined),refreshing=useRef(false),metadataError=useRef(''),onNewRef=useRef(onNew),onUnreadRef=useRef(onUnread),log=useRef<HTMLDivElement>(null),selectedRef=useRef(selected),recordsRef=useRef(records),autoAttempt=useRef(''),autoPaused=useRef(false);
  onNewRef.current=onNew;onUnreadRef.current=onUnread;selectedRef.current=selected;recordsRef.current=records;
  const peer=friends.find(f=>f.id===selected&&f.status===1);
  const[ordinaryOutbox,setOrdinaryOutbox]=useState<OrdinaryPending>();const ordinaryPending=!!ordinaryOutbox;
  const screenHidden=usePrivateScreen();
  const ordinary=!!peer&&peer.allow_server!==false;
  const canChat=!ordinary&&trusted&&!!peer?.public_key&&!!peer?.device;
  function safeClose(){if(ordinaryPending){setStatus('请先重试或放弃普通聊天待发消息，再关闭好友。');return;}close();}
  async function refresh(){if(refreshing.current)return;refreshing.current=true;try{const own=await api<Me>('/friends/me');if(!alive.current)return;setMe(own);const data=await api<{friends:Friend[];unread:number;latest_message:number}>('/friends');if(!alive.current)return;setFriends(data.friends);const next={latest:data.latest_message,relations:data.friends};for(const event of friendEvents(snapshot.current,next,own.id))onNewRef.current(event);snapshot.current={...next,latest:Math.max(next.latest,snapshot.current?.latest??0)};onUnreadRef.current(data.unread+data.friends.filter(f=>f.status===0&&f.requester!==own.id).length);const previousError=metadataError.current;metadataError.current='';setStatus(value=>value===previousError?'':value);const state=engine.current;if(state&&own.prekeys_left<8&&!operation.current){operation.current=true;try{const pre=JSON.parse(state.engine.prekeys());await persist(state);await privateApi(state,'/device',{password:'',device:state.saved.device,lease:state.saved.lease,...pre});}finally{finishOperation();}}}finally{refreshing.current=false;}}
  function dispose(){engine.current?.engine.free();engine.current=undefined;localRelease.current?.();localRelease.current=undefined;}
  function finishOperation(){operation.current=false;if(!alive.current)dispose();}
  function lock(){if(operation.current){setStatus('正在保存加密状态，请稍后锁定。');return;}autoPaused.current=true;dispose();setUnlocked(false);setRecords([]);setDraft('');setImage('');}
  useEffect(()=>{alive.current=true;const update=()=>{void refresh().catch(e=>{if(alive.current){metadataError.current=e.message;setStatus(e.message);}});};update();const t=setInterval(update,10000);window.addEventListener('focus',update);document.addEventListener('visibilitychange',update);return()=>{alive.current=false;clearInterval(t);window.removeEventListener('focus',update);document.removeEventListener('visibilitychange',update);if(!operation.current)dispose();};},[]);
  useEffect(()=>{if(!me)return;void loadLocal<Encrypted>('keys',`identity:${me.id}`).then(v=>{if(alive.current)setBackup(v);}).catch(e=>setStatus(e.message));},[me?.id]);
  useEffect(()=>{if(open&&!inline&&compact)dialog.current?.showModal();else dialog.current?.close();},[open,inline,compact]);
  useEffect(()=>{let cancelled=false;setTrusted(false);setConfirmTrust(false);setSafety('');setBefore(0);setRecords([]);setDraft('');setImage('');if(me?.public_key&&peer?.public_key)void Promise.all([safetyCode(me.public_key,peer.public_key),loadLocal<string>('trust',`${me.id}:${peer.id}`)]).then(([code,key])=>{if(cancelled)return;setSafety(code);setTrusted(key===peer.public_key);if(key&&key!==peer.public_key)setStatus('对方身份已变化，私信停止。请通过其他渠道重新核对安全码。');}).catch(e=>setStatus(e.message));return()=>{cancelled=true;};},[selected,peer?.public_key,me?.public_key]);
  useEffect(()=>{if(!open||!peer||!canChat||!unlocked||ordinary||screenHidden)return;let stopped=false;const t=setInterval(()=>{if(!stopped&&document.visibilityState==='visible')void receive().catch(e=>setStatus(e.message));},5000);void receive().catch(e=>setStatus(e.message));return()=>{stopped=true;clearInterval(t);};},[open,peer?.id,canChat,unlocked,before,ordinary,screenHidden]);
  useEffect(()=>{if(!open||ordinary||!showKeys||unlocked||!backup?.automatic||!me?.public_key||autoPaused.current||operation.current)return;const id=`${me.id}:${me.public_key}`;if(autoAttempt.current===id)return;autoAttempt.current=id;void unlock(false,true);},[open,backup,me?.public_key,unlocked,ordinary,showKeys]);
  useEffect(()=>{const t=setInterval(()=>{setRecords(rows=>{const now=Date.now(),active=rows.filter(r=>r.expires>now/1000&&(!r.burnAt||r.burnAt>now));return active.length===rows.length?rows:active;});},1000);return()=>clearInterval(t);},[]);
  useEffect(()=>{if(log.current&&before===0)log.current.scrollTop=log.current.scrollHeight;},[records.length,before]);
  async function browserLock(id:number){
    if(!navigator.locks)throw new Error('浏览器不支持安全的设备状态锁，请使用新版浏览器。');
    await new Promise<void>((resolve,reject)=>{void navigator.locks.request(`webts-olm-${id}`,{ifAvailable:true},async l=>{if(!l){reject(new Error('另一标签页正在处理加密私信，请先在那一页锁定私信。'));return;}await new Promise<void>(done=>{localRelease.current=done;resolve();});}).catch(reject);});
  }
  async function activateDevice(state:Unlocked,credential:string){
    if(!state.saved.previousLease){state.saved.previousLease=state.saved.lease;state.saved.lease=Array.from(crypto.getRandomValues(new Uint8Array(32)),b=>b.toString(16).padStart(2,'0')).join('');}
    const pre=JSON.parse(state.engine.prekeys()),body={password:credential,device:state.saved.device,lease:state.saved.lease,...pre};await persist(state);
    try{await privateApi({...state,saved:{...state.saved,lease:state.saved.previousLease}},'/device',body);}
    catch(e){if(credential||(e as {status?:number}).status!==409)throw e;await privateApi(state,'/device',body);}
    delete state.saved.previousLease;await persist(state);
  }
  async function unlock(create:boolean,silent=false){if(!me||operation.current)return;operation.current=true;setBusy(true);setStatus('');let state:Unlocked|undefined;
    try{await browserLock(me.id);let identity=backup;
      if(create){if(!automatic&&passphrase!==confirm)throw new Error('两次密钥口令不同');identity=automatic?await createAutomaticIdentity(me.id):await createIdentity(me.id,passphrase);await saveLocal('keys',`identity:${me.id}`,identity);setBackup(identity);}
      if(!identity)throw new Error('请先导入私信身份备份');const own=await api<Me>('/friends/me');setMe(own);
      if(!own.public_key){await api('/friends/key',{password,public_key:identity.publicKey});own.public_key=identity.publicKey;}
      const local=await loadLocal<Encrypted>('keys',`state:${me.id}`);state=await unlockState(identity,local,me.id,own.public_key,passphrase);
      if(automatic&&!identity.automatic){identity=await rememberDevice(identity,state,passphrase);setBackup(identity);}
      await activateDevice(state,password);
      if(!alive.current){state.engine.free();localRelease.current?.();return;}
      engine.current=state;autoPaused.current=false;setUnlocked(true);setShowKeys(false);setStatus(state.record.automatic?'此设备已自动解锁。密钥留在本浏览器；可在“设备与备份”中选择备份。':'私信已解锁。');await flushOutbox(state);await refresh();
    }catch(e){if(state&&engine.current===state){dispose();setUnlocked(false);}else{state?.engine.free();localRelease.current?.();localRelease.current=undefined;}setStatus(`${e instanceof Error?e.message:'解锁失败'}${silent?'。如被其他设备接管，请输入网站密码重新确认；本机密钥丢失时需导入备份。':''}`);}finally{setPassphrase('');setConfirm('');setPassword('');setBusy(false);finishOperation();}
  }
  async function exportBackup(){if(!me||!backup||operation.current)return;operation.current=true;setBusy(true);try{if(passphrase!==confirm)throw new Error('两次备份口令不同');await api('/friends/key',{password,public_key:backup.publicKey});download(await exportIdentity(backup,passphrase));setStatus('已下载受独立口令保护的身份备份。口令不发送给网站。');}catch(e){setStatus(e instanceof Error?e.message:'备份失败');}finally{setPassword('');setPassphrase('');setConfirm('');setBusy(false);finishOperation();}}
  async function importIdentity(file:File){if(unlocked||operation.current)return;operation.current=true;setBusy(true);try{if(!me||file.size>128*1024)throw new Error('请选择128KiB以内的身份备份');const value:Encrypted=JSON.parse(await file.text());if(value.automatic||value.account!==me.id||value.version!==1||value.kind!=='identity')throw new Error('需要当前账号的口令备份，设备自动密钥不能作为导入文件');if(me.public_key&&value.publicKey!==me.public_key)throw new Error('备份与登记公钥不一致');const checked=await unlockState(value,undefined,me.id,value.publicKey,passphrase);checked.engine.free();if(!window.confirm('导入将替换本机私信状态，接管后旧临时消息会过期。继续？'))return;await saveImportedIdentity(value);setBackup(value);setStatus('备份口令与身份已验证，请输入网站密码启用此设备。');}catch(e){setStatus(e instanceof Error?e.message:'导入失败');}finally{setBusy(false);finishOperation();}}
  async function chooseEncryption(allow:boolean){if(!peer||operation.current)return;operation.current=true;setBusy(true);try{if(engine.current?.saved.outbox)throw new Error('请先重试或放弃端到端待发消息，再切换模式');await api(`/friends/${peer.id}/encryption`,{server_decrypt:allow,acknowledge:allow});if(!allow&&!unlocked)setShowKeys(true);else setShowKeys(false);await refresh();setStatus(allow?'已选择普通聊天，可直接发送，对方离线也会加密保存至对象存储。':'已选择端到端加密，请启用设备身份并核对安全码。');}catch(e){setStatus(e instanceof Error?e.message:'选择失败');}finally{setBusy(false);finishOperation();}}
  async function friendship(id:number,action:string){if(ordinaryPending){setStatus('请先重试或放弃待发消息。');return;}setBusy(true);try{await api(`/friends/${id}`,{action});if(id===selected){setSelected(undefined);setRecords([]);}await refresh();}catch(e){setStatus(e instanceof Error?e.message:'操作失败');}finally{setBusy(false);}}
  async function flushOutbox(state:Unlocked){const pending=state.saved.outbox;if(!pending)return;await privateApi(state,'/messages',pending);delete state.saved.outbox;await persist(state);}
  async function send(sticker?:string){if(!me||!peer||!engine.current||operation.current)return;if(!canChat){setStatus('端到端发送需要启用设备并核对安全码；普通聊天可直接发送。');return;}if(!draft.trim()&&!image&&!sticker)return;operation.current=true;setBusy(true);setStatus('');const state=engine.current;let snapshot=state.engine.save();let savedSnapshot=structuredClone(state.saved);let stored=false;
    try{if(!me.storage_enabled)throw new Error('管理员尚未配置私有对象存储；不会发送明文。');await flushOutbox(state);snapshot=state.engine.save();savedSnapshot=structuredClone(state.saved);const root=JSON.parse(peer.public_key),mode='e2ee' as const,epoch=peer.mode_epoch??0;
      if(mode==='e2ee'&&(!state.engine.has_session(root.curve)||state.saved.peerDevices[peer.id]!==peer.device)){const claimed=await privateApi<{key:string;bundle:{payload:string;signature:string;device:string}}>(state,`/${peer.id}/prekey`,{});const target=await checkPrekey(peer.public_key,claimed);state.engine.outbound(target.curve,claimed.key);state.saved.peerDevices[peer.id]=target.device;}
      const id=crypto.randomUUID(),value:Envelope={version:1,site:location.origin,id,sender:me.id,recipient:peer.id,expires:Math.floor(Date.now()/1000)+me.retention_days*86400,text:draft,image:image||undefined,sticker,burn,burn_seconds:burn?burnSeconds:undefined};
      const ciphertext=await sealMessage(value,state,root.curve,state.saved.peerDevices[peer.id]);state.saved.outbox={peer:peer.id,id,ciphertext,burn,burn_seconds:value.burn_seconds,mode,epoch};if(!burn||value.burn_seconds)state.saved.cache[id]={value,created_at:Date.now()/1000,mode,epoch};await persist(state);stored=true;setDraft('');setImage('');
      await flushOutbox(state);setStatus(burn?'阅后即焚密文已发送，对方成功解密并确认已读后开始倒计时。':'加密私信已送达');
    }catch(e){if(!stored&&alive.current&&engine.current===state){const m=await cryptoModule();state.engine.free();state.engine=m.Engine.restore(snapshot);state.saved=savedSnapshot;}setStatus(`${e instanceof Error?e.message:'发送失败'}${stored?'；密文已保留在本机待发箱，点击重试将发送同一份密文。':''}`);}finally{setBusy(false);finishOperation();}
    if(stored)void receive().catch(e=>setStatus(e.message));
  }
  async function receive(){const state=engine.current;if(document.hidden||!document.hasFocus()||!state||!me||!peer||operation.current||!trusted||ordinary)return;operation.current=true;const target=peer.id;
    try{const display:Display[]=[];let cacheChanged=false;
      for(const id of state.saved.readPending??[]){try{const ack=await privateApi<{expires:number}>(state,`/messages/${id}/read`,{});applyReadReceipt(state.saved.cache[id],ack.expires);state.saved.readPending=state.saved.readPending?.filter(v=>v!==id);await persist(state);}catch(e){if((e as {status?:number}).status===404){state.saved.readPending=state.saved.readPending?.filter(v=>v!==id);await persist(state);}}}
      const data=await privateApi<{messages:Message[]}>(state,`/${target}/messages${before?`?before=${before}`:''}`);
      for(const row of [...data.messages].reverse()){
        if(!alive.current||selectedRef.current!==target||engine.current!==state)return;if(row.mode==='server')continue;const cached=state.saved.cache[row.id];if(row.burn&&!row.burn_seconds&&recordsRef.current.some(r=>r.id===row.id&&r.value))continue;
        if(cached&&(!row.burn||row.burn_seconds)&&(cached.mode??'e2ee')===(row.mode??'e2ee')&&(cached.epoch??0)===(row.epoch??0)){
          try{const previousExpires=cached.value.expires,previousBurn=cached.burnAt;validEnvelope(cached.value,{site:location.origin,id:row.id,sender:row.sender,recipient:row.recipient,burn:row.burn,burn_seconds:row.burn_seconds??undefined});cached.value.expires=Math.min(cached.value.expires,row.expires);if(row.read_at!==null)applyReadReceipt(cached,row.expires);cacheChanged||=previousExpires!==cached.value.expires||previousBurn!==cached.burnAt;if(cached.value.expires>Date.now()/1000&&(!cached.burnAt||cached.burnAt>Date.now()))display.push({...row,value:cached.value,burnAt:cached.burnAt});}catch(e){display.push({...row,error:e instanceof Error?e.message:'焚毁策略不匹配'});}continue;
        }
        if(row.sender===me.id){display.push({...row,error:row.burn&&!row.burn_seconds?'旧版阅后即焚消息不保留本地正文':'本机没有此消息的历史缓存'});continue;}
        const snapshot=state.engine.save();let durable=false;
        try{const result=await privateApi<{ciphertext:string}>(state,`/messages/${row.id}`);if(!alive.current||engine.current!==state||selectedRef.current!==target)return;const expected={site:location.origin,id:row.id,sender:row.sender,recipient:row.recipient,burn:row.burn,burn_seconds:row.burn_seconds??undefined};const value=await openMessage(result.ciphertext,state,JSON.parse(peer.public_key).curve,expected);value.expires=Math.min(value.expires,row.expires);if(value.expires<=Date.now()/1000)throw new Error('消息已过期');
          if(!row.burn||value.burn_seconds)state.saved.cache[row.id]={value,created_at:row.created_at,mode:row.mode??'e2ee',epoch:row.epoch??0,burnAt:value.burn_seconds?Math.min(value.expires*1000,Date.now()+value.burn_seconds*1000):undefined};state.saved.readPending=[...(state.saved.readPending??[]).filter(v=>v!==row.id),row.id];await persist(state);durable=true;
          if(document.hidden||!document.hasFocus())return;
          // Acknowledge only after authentication, decryption and durable ratchet state saving.
          try{const ack=await privateApi<{expires:number}>(state,`/messages/${row.id}/read`,{});applyReadReceipt(state.saved.cache[row.id],ack.expires);state.saved.readPending=state.saved.readPending?.filter(v=>v!==row.id);await persist(state);}catch{setStatus('消息已安全解密，已读 / 焚毁确认等待重试。');}display.push({...row,value,burnAt:row.burn?(state.saved.cache[row.id]?.burnAt??Date.now()+60000):undefined});
        }catch(e){if(!alive.current||engine.current!==state)return;if(!durable){const m=await cryptoModule();state.engine.free();state.engine=m.Engine.restore(snapshot);delete state.saved.cache[row.id];state.saved.readPending=state.saved.readPending?.filter(v=>v!==row.id);}display.push({...row,error:e instanceof Error?e.message:'消息解密失败'});}
      }
      if(cacheChanged||Object.values(state.saved.cache).some(v=>v.value.expires<=Date.now()/1000||!!v.burnAt&&v.burnAt<=Date.now()))await persist(state);
      if(alive.current&&selectedRef.current===target){setRecords(old=>{const liveBurn=old.filter(r=>!r.burn_seconds&&r.burnAt&&r.burnAt>Date.now());return [...display.filter(r=>!liveBurn.some(b=>b.id===r.id)),...liveBurn].sort((a,b)=>a.seq-b.seq);});}await refresh();
    }finally{finishOperation();}
  }
  const content=<section className={`friends-layout ${peer||showKeys?'show-conversation':''}`} aria-label="好友与端到端加密私信">
    <aside className="friends-list"><header><div><small>WEBTS FRIENDS</small><h2>好友</h2></div><button className="icon-button" aria-label="关闭好友" onClick={safeClose}>×</button></header><div className="friend-self"><span className="avatar">{profile?.avatar?<img src={`data:image/png;base64,${profile.avatar}`} alt="我的头像"/>:(profile?.display_name||'我').slice(0,1)}</span><div><strong>{profile?.display_name||`WebTS 用户 ${me?.id??''}`}</strong><small>社区账号 · 无需连接TS</small></div></div><p className="muted">普通私信无需私信身份；端到端加密可选。原生 TS 私聊独立使用。</p>
      {me&&<label className="checkbox friend-presence-choice"><input type="checkbox" checked={me.share_presence} onChange={async e=>{try{await api('/friends/presence',{share:e.target.checked});await refresh();}catch(e){setStatus(e instanceof Error?e.message:'保存失败');}}}/>向好友显示在线状态和所在频道</label>}{me&&<div className="friend-code"><small>我的好友码</small><code>{me.code}</code><button className="text-button" onClick={()=>navigator.clipboard.writeText(me.code).then(()=>setStatus('好友码已复制')).catch(()=>setStatus('请手动复制好友码'))}>复制</button></div>}
      <form onSubmit={async e=>{e.preventDefault();setBusy(true);try{await api('/friends/request',{code:code.trim()});setCode('');await refresh();setStatus('请求已发送，对方接受后可核对安全码。');}catch(e){setStatus(e instanceof Error?e.message:'添加失败');}finally{setBusy(false);}}}><label>添加好友<input value={code} onChange={e=>setCode(e.target.value)} placeholder="粘贴对方好友码" maxLength={24} required/></label><button className="secondary full" disabled={busy||!me}>发送好友请求</button></form>
      <div className="friend-rows">{friends.filter(f=>f.status===1).map(f=><button className={`friend-row ${f.id===selected?'active':''}`} key={f.id} disabled={ordinaryPending} onClick={()=>setSelected(f.id)}><FriendAvatar friend={f}/><span><strong>{title(f)}</strong><small>{f.online?'● 在线':'○ 离线 / 已隐藏'}{f.locations?.length?` · ${f.locations[0].location.channel_name}`:''}</small></span><span>›</span></button>)}{friends.filter(f=>f.status!==1).map(f=><article className="friend-request" key={f.id}><div className="friend-request-identity"><FriendAvatar friend={f}/><strong>{title(f)}</strong></div><small>{f.status===2?'已屏蔽':f.requester===me?.id?'等待对方接受':'请求添加你为好友'}</small><div>{f.status===0&&f.requester!==me?.id&&<button disabled={busy} className="text-button" onClick={()=>friendship(f.id,'accept')}>接受</button>}<button disabled={busy||f.status===2&&f.blocked_by!==me?.id} className="text-button" onClick={()=>friendship(f.id,f.status===2?'unblock':'decline')}>{f.status===2?'解除屏蔽':'取消 / 拒绝'}</button></div></article>)}</div>
      {!unlocked&&<button className="primary full" disabled={ordinaryPending} onClick={()=>setShowKeys(true)}>端到端设备与备份</button>}
      {unlocked&&<><button className="secondary full" disabled={ordinaryPending} onClick={()=>setShowKeys(true)}>设备与备份</button><button className="text-button full" onClick={lock} disabled={busy||ordinaryPending}>锁定本机私信</button></>}
    </aside>
    <section className={`friend-conversation ${(peer&&!ordinary||showKeys)&&screenHidden?'private-screen-masked':''}`}><p className="private-screen-notice" role="status">端到端会话已黑屏 · 返回并聚焦窗口后显示。这不是系统截图或外部录屏检测。</p><header className="friend-heading"><button className="friend-back" disabled={ordinaryPending} onClick={()=>{setSelected(undefined);setShowKeys(false);}} aria-label="返回好友列表">‹</button>{peer&&<FriendAvatar friend={peer}/>}<div><small>{ordinary?'普通私信 · AES-256-GCM':'端到端加密 · AES-256-GCM / OLM'}</small><h2>{showKeys?'设备与备份':peer?title(peer):'好友私信'}</h2>{peer?.about&&<p className="friend-about" title={peer.about}>{peer.about}</p>}</div>{peer&&<button className="text-button danger" disabled={busy} onClick={()=>{if(window.confirm(`屏蔽 ${title(peer)} 并清理双方临时消息？`))void friendship(peer.id,'block');}}>屏蔽</button>}</header>
      {status&&<p className="friend-status" role="status">{status}</p>}
      {ordinaryOutbox&&!ordinary&&<p role="alert">发送方式已改变；待发密文不会自动降级或重发。<button className="text-button" onClick={()=>{if(window.confirm('放弃旧模式待发密文？服务器若已收到仍可能送达。'))setOrdinaryOutbox(undefined);}}>放弃旧待发消息</button></p>}{peer&&<><div className="friend-location"><span className={`dot ${peer.online?'online':''}`}/><span>{peer.online?'在线':'离线 / 已隐藏'}</span>{peer.locations?.map(where=><div key={where.connection}><strong>{where.location.server_name} · {where.location.channel_name}</strong><button className="secondary small" disabled={busy} onClick={()=>{void onJoin(peer.id,where).catch(e=>setStatus(e instanceof Error?e.message:'加入失败'));}}>加入频道{where.location.password?' 🔒':''}</button></div>)}</div><div className="friend-mode-choice"><button className="secondary small" disabled={busy||ordinaryPending||!!peer.allow_server&&ordinary} onClick={()=>void chooseEncryption(true)}>普通聊天 · 无需私信身份</button><button className="secondary small" disabled={busy||ordinaryPending} onClick={()=>{if(peer.allow_server)void chooseEncryption(false);else if(!unlocked)setShowKeys(true);}}>端到端加密 · 配置设备身份</button><small>普通消息加密存入对象存储，离线也可发送；本站可以解密。端到端与普通消息分别查看。</small></div></>}
      {ordinary&&peer&&me&&!showKeys?<OrdinaryChat key={`${me.id}:${peer.id}:${peer.mode_epoch}`} account={me.id} peer={peer.id} name={title(peer)} epoch={peer.mode_epoch??0} active={open} enabled={me.storage_enabled} days={me.retention_days} refresh={refresh} pending={ordinaryOutbox} setPending={setOrdinaryOutbox}/>:!unlocked&&!showKeys?<div className="chat-empty"><p>选择好友和聊天方式</p><small>普通聊天以账号保护隐私，无需配置额外口令。<br/>端到端加密需设备身份与安全码核验；Olm 协议与 Signal 不同。</small></div>:!unlocked||showKeys?<div className="friend-key-setup"><h3>{unlocked?'可选的身份备份':me?.public_key?'此设备的私信身份':'一键启用私信'}</h3><p>默认自动生成设备密钥，不用另记私信口令。同一设备可自动解锁；密钥留在本浏览器，不发送给网站。清理浏览器或更换设备需要可选备份。</p><p>一次一台设备处理私信；新设备接管会使旧临时消息过期。自动模式的密钥和密文均在本机，同源网页脚本可以使用密钥；备份可另设口令。</p>
        {!unlocked&&(!backup||!backup.automatic)&&<label className="checkbox"><input type="checkbox" checked={automatic} onChange={e=>setAutomatic(e.target.checked)}/>在此浏览器自动保存和解锁设备密钥</label>}
        {(unlocked||backup&&!backup.automatic||!automatic)&&<><label>{unlocked?backup?.automatic?'备份口令（16–256字符）':'原私信口令（备份沿用原口令）':'原私信口令 / 导入备份口令'}<input type="password" value={passphrase} autoComplete="off" onChange={e=>setPassphrase(e.target.value)} minLength={16} maxLength={256}/></label>{(unlocked||!me?.public_key&&!backup&&!automatic)&&<label>再次输入口令<input type="password" autoComplete="off" value={confirm} onChange={e=>setConfirm(e.target.value)}/></label>}</>}
        <label>网站账号密码（首次启用、换设备或导出备份时确认）<input type="password" autoComplete="current-password" value={password} onChange={e=>setPassword(e.target.value)}/></label>
        {!unlocked?<button className="primary full" disabled={busy||!me?.public_key&&!password||!!me?.public_key&&!backup||!!backup&&!backup.automatic&&!passphrase||!backup&&!automatic&&!passphrase} onClick={()=>unlock(!me?.public_key&&!backup)}>{busy?'正在处理…':me?.public_key||backup?'解锁此设备':'自动生成并启用私信'}</button>:<><button className="primary full" disabled={busy||!password||!passphrase||!confirm} onClick={()=>void exportBackup()}>下载口令加密的身份备份</button><button className="text-button" onClick={()=>setShowKeys(false)}>返回对话</button></>}
        {!unlocked&&<details><summary>我有其他设备的身份备份</summary><label>导入备份的口令<input type="password" autoComplete="off" value={passphrase} onChange={e=>setPassphrase(e.target.value)} maxLength={256}/></label><label className="secondary file-button">导入身份备份（先填备份口令）<input type="file" accept="application/json,.json" disabled={busy||!passphrase} onChange={e=>{const f=e.target.files?.[0];e.target.value='';if(f)void importIdentity(f);}}/></label></details>}{backup&&!backup.automatic&&<button className="text-button" onClick={()=>download(backup)}>下载现有口令备份</button>}
      </div>:peer?<><details className="friend-protection" open={!canChat}><summary>端到端加密 · 身份与加密设置</summary>{!peer.public_key||!peer.device?<p className="friend-status">好友尚未在设备上启用私信；可以先保留好友关系，启用后再核对安全码。</p>:<section className="friend-safety"><div><strong>{trusted?'已核对好友身份':'核对安全码后开始聊天'}</strong><small>请通过当面或另一可信渠道与对方核对，双方代码应完全一致。</small><code>{safety||'正在计算…'}</code></div>{!trusted&&<><label className="checkbox"><input type="checkbox" checked={confirmTrust} onChange={e=>setConfirmTrust(e.target.checked)}/>我已与好友核对安全码一致</label><button className="secondary small" disabled={!confirmTrust||!safety} onClick={async()=>{if(!me)return;await saveLocal('trust',`${me.id}:${peer.id}`,peer.public_key);setTrusted(true);setStatus('好友身份已固定在此设备。');}}>信任此身份</button></>}</section>}</details>
        <div className="friend-messages" ref={log} role="log" aria-label="端到端私信消息">{records.length>=30&&<button className="text-button" disabled={busy} onClick={()=>setBefore(records[0].seq)}>更早的临时消息</button>}{before>0&&<button className="text-button" onClick={()=>setBefore(0)}>返回最新消息</button>}{records.length===0&&<div className="chat-empty"><span className="friend-lock">♢</span><p>{canChat?'开始一段加密对话':'安全码核对前不会解密或发送消息'}</p><small>默认 {me?.retention_days??7} 天后过期 · 临时图片一并加密</small></div>}{records.map(row=><article className={`friend-message ${row.sender===me?.id?'self':''}`} key={row.id}><small>{row.sender===me?.id?'你':title(peer)} · {new Date(row.created_at*1000).toLocaleTimeString([], {hour:'2-digit',minute:'2-digit'})}{row.mode==='server'?' · 本站可解密':' · E2EE'}{row.burn?' · 阅后即焚':''}</small>{row.value?<><p>{row.value.text}</p>{row.value.image&&<img src={row.value.image} alt="加密聊天图片" loading="lazy"/>}{row.value.sticker&&<Sticker id={row.value.sticker}/>}</>:<p className="muted">{row.error??'等待解密'}</p>}{row.burnAt&&<small>{row.burn_seconds?`已读后 ${burnDurations.find(([seconds])=>seconds===row.burn_seconds)?.[1]??'所选时间'}焚毁，最晚 ${new Date(row.burnAt).toLocaleString()} 到期。`:'旧版阅后即焚：服务器已禁止读取，本页最多显示60秒。'}对方仍可截图或保存。</small>}</article>)}</div>
        {image&&<div className="friend-attachment"><img src={image} alt="待发加密图片"/><button className="text-button danger" onClick={()=>setImage('')}>移除图片</button></div>}
        <div className="friend-compose-options"><label className="checkbox"><input type="checkbox" checked={burn} onChange={e=>setBurn(e.target.checked)}/>阅后即焚</label>{burn&&<label className="friend-burn-duration">已读后<select aria-label="阅后即焚时长" value={burnSeconds} onChange={e=>setBurnSeconds(Number(e.target.value))}>{burnDurations.map(([seconds,label])=><option key={seconds} value={seconds}>{label}</option>)}</select></label>}<label className="text-button file-button">图片 / 自定义表情<input type="file" accept="image/png,image/jpeg,image/webp" disabled={busy||!canChat} onChange={e=>{const file=e.target.files?.[0];e.target.value='';if(file)setCrop(file);}}/></label>{engine.current?.saved.outbox&&<button className="text-button" disabled={busy} onClick={async()=>{const state=engine.current;if(!state||operation.current)return;operation.current=true;setBusy(true);try{await flushOutbox(state);setStatus('待发密文已送达');}catch(e){setStatus(e instanceof Error?e.message:'重试失败');}finally{finishOperation();setBusy(false);}}}>重试待发消息</button>}{engine.current?.saved.outbox&&<button className="text-button danger" disabled={busy} onClick={async()=>{const state=engine.current;if(!state||operation.current||!window.confirm("放弃待发消息？若服务器已收到，它仍可能送达；此操作不会撤回。"))return;operation.current=true;setBusy(true);try{delete state.saved.outbox;await persist(state);setStatus("待发密文已放弃，棘轮状态已保留。");}catch(e){setStatus(e instanceof Error?e.message:"保存失败");}finally{finishOperation();setBusy(false);}}}>放弃待发消息</button>}</div>
        <form className="composer friend-composer" onSubmit={e=>{e.preventDefault();void send();}}><StickerPicker privacy="e2ee" emoji={t=>setDraft(v=>(v+t).slice(0,4096))} sticker={id=>{void send(id);}}/><input aria-label="好友加密私信内容" value={draft} onChange={e=>setDraft(e.target.value)} maxLength={4096} disabled={!canChat||busy} placeholder={canChat?'发送端到端加密私信…':'先核对安全码'}/><button disabled={!canChat||busy||!me?.storage_enabled||!draft.trim()&&!image} aria-label="发送加密私信">➜</button></form>
      </>:<div className="chat-empty"><span className="friend-lock">♢</span><p>选择好友即可普通聊天</p><small>成熟 Olm 双棘轮 · 与 Signal 协议不同<br/>手机与电脑都能使用；密文临时保存至私有对象存储。</small></div>}
    </section>
  </section>;
  const tools=<header className="friends-shell-head"><strong>好友与私信</strong><div>{!compact&&changeDisplay&&<button className="secondary small" aria-label={display==='docked'?'切换为悬浮好友':'切换为停靠好友'} onClick={()=>changeDisplay(display==='docked'?'floating':'docked')}>{display==='docked'?'↗ 悬浮':'▥ 停靠'}</button>}<button className="icon-button" aria-label="关闭好友面板" onClick={safeClose}>×</button></div></header>;
  return <>{inline?<div className="friends-mobile-page" hidden={!open}>{content}</div>:compact?<dialog ref={dialog} className="friends-dialog" aria-label="WebTS 好友与加密私信" onCancel={e=>{e.preventDefault();safeClose();}}>{content}</dialog>:<section className={`friends-panel friends-${display}`} hidden={!open} aria-label="WebTS 好友与加密私信">{tools}{content}</section>}{crop&&(!screenHidden||ordinary)&&<ImageCropper file={crop} purpose="content" onCancel={()=>setCrop(undefined)} onComplete={value=>{setImage(value);setCrop(undefined);}}/>}</>;
}
