import {useEffect,useRef,useState} from 'react';
import {api} from './api';
import {ImageCropper} from './ImageCropper';
import {Sticker,StickerPicker} from './Stickers';
import {checkPrekey,createIdentity,cryptoModule,loadLocal,openMessage,persist,safetyCode,saveLocal,sealMessage,unlockState} from './friend-crypto';
import type {Encrypted,Envelope,Unlocked} from './friend-crypto';
type Me={id:number;code:string;public_key:string;storage_enabled:boolean;retention_days:number;prekeys_left:number};
type Friend={id:number;name:string;public_key:string;device:string;requester:number;status:number;blocked_by:number};
type Message={seq:number;id:string;sender:number;recipient:number;created_at:number;expires:number;burn:boolean;read_at:number|null};
type Display=Message&{value?:Envelope;error?:string;burnAt?:number};
const title=(friend:Friend)=>friend.name||`WebTS 用户 ${friend.id}`;
async function privateApi<T>(state:Unlocked,path:string,body?:unknown):Promise<T>{
  const r=await fetch(`/api/friends${path}`,{method:body===undefined?'GET':'POST',credentials:'same-origin',headers:{'x-webts-chat-device':state.saved.lease,...(body===undefined?{}:{'content-type':'application/json'})},body:body===undefined?undefined:JSON.stringify(body)});
  if(!r.ok){const data=await r.json().catch(()=>null);throw Object.assign(new Error(data?.error??'加密私信请求失败'),{status:r.status});}return r.json();
}
function download(record:Encrypted){const url=URL.createObjectURL(new Blob([JSON.stringify(record)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download=`webts-private-identity-${record.account}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
export function Friends({open,inline,close,onUnread,onNew}:{open:boolean;inline:boolean;close:()=>void;onUnread:(count:number)=>void;onNew:()=>void}){
  const[me,setMe]=useState<Me>(),[friends,setFriends]=useState<Friend[]>([]),[selected,setSelected]=useState<number>(),[records,setRecords]=useState<Display[]>([]),[draft,setDraft]=useState(''),[image,setImage]=useState(''),[crop,setCrop]=useState<File>(),[burn,setBurn]=useState(false),[status,setStatus]=useState(''),[busy,setBusy]=useState(false),[passphrase,setPassphrase]=useState(''),[confirm,setConfirm]=useState(''),[password,setPassword]=useState(''),[backup,setBackup]=useState<Encrypted>(),[unlocked,setUnlocked]=useState(false),[code,setCode]=useState(''),[safety,setSafety]=useState(''),[trusted,setTrusted]=useState(false),[confirmTrust,setConfirmTrust]=useState(false),[before,setBefore]=useState(0),[showKeys,setShowKeys]=useState(false);
  const engine=useRef<Unlocked|undefined>(undefined),dialog=useRef<HTMLDialogElement>(null),localRelease=useRef<(()=>void)|undefined>(undefined),operation=useRef(false),alive=useRef(true),knownUnread=useRef<number|undefined>(undefined),onNewRef=useRef(onNew),onUnreadRef=useRef(onUnread),log=useRef<HTMLDivElement>(null),selectedRef=useRef(selected),recordsRef=useRef(records);
  onNewRef.current=onNew;onUnreadRef.current=onUnread;selectedRef.current=selected;recordsRef.current=records;
  const peer=friends.find(f=>f.id===selected&&f.status===1);
  async function refresh(){const own=await api<Me>('/friends/me');if(!alive.current)return;setMe(own);const data=await api<{friends:Friend[];unread:number}>('/friends');if(!alive.current)return;setFriends(data.friends);onUnreadRef.current(data.unread);if(knownUnread.current!==undefined&&data.unread>knownUnread.current)onNewRef.current();knownUnread.current=data.unread;const state=engine.current;if(state&&own.prekeys_left<8&&!operation.current){operation.current=true;try{const pre=JSON.parse(state.engine.prekeys());await persist(state);await privateApi(state,'/device',{password:'',device:state.saved.device,lease:state.saved.lease,...pre});}finally{finishOperation();}}}
  function dispose(){engine.current?.engine.free();engine.current=undefined;localRelease.current?.();localRelease.current=undefined;}
  function finishOperation(){operation.current=false;if(!alive.current)dispose();}
  function lock(){if(operation.current){setStatus('正在保存加密状态，请稍后锁定。');return;}dispose();setUnlocked(false);setRecords([]);setDraft('');setImage('');}
  useEffect(()=>{alive.current=true;void refresh().catch(e=>setStatus(e.message));const t=setInterval(()=>{if(document.visibilityState==='visible')void refresh().catch(e=>setStatus(e.message));},10000);return()=>{alive.current=false;clearInterval(t);if(!operation.current)dispose();};},[]);
  useEffect(()=>{if(!me)return;void loadLocal<Encrypted>('keys',`identity:${me.id}`).then(v=>{if(alive.current)setBackup(v);}).catch(e=>setStatus(e.message));},[me?.id]);
  useEffect(()=>{if(open&&!inline)dialog.current?.showModal();else dialog.current?.close();},[open,inline]);
  useEffect(()=>{let cancelled=false;setTrusted(false);setConfirmTrust(false);setSafety('');setBefore(0);setRecords([]);setDraft('');setImage('');if(me&&peer)void Promise.all([safetyCode(me.public_key,peer.public_key),loadLocal<string>('trust',`${me.id}:${peer.id}`)]).then(([code,key])=>{if(cancelled)return;setSafety(code);setTrusted(key===peer.public_key);if(key&&key!==peer.public_key)setStatus('对方身份已变化，私信停止。请通过其他渠道重新核对安全码。');}).catch(e=>setStatus(e.message));return()=>{cancelled=true;};},[selected,peer?.public_key,me?.public_key]);
  useEffect(()=>{if(!open||!peer||!trusted||!unlocked)return;let stopped=false;const t=setInterval(()=>{if(!stopped&&document.visibilityState==='visible')void receive().catch(e=>setStatus(e.message));},5000);void receive().catch(e=>setStatus(e.message));return()=>{stopped=true;clearInterval(t);};},[open,peer?.id,trusted,unlocked,before]);
  useEffect(()=>{const t=setInterval(()=>{setRecords(rows=>rows.filter(r=>r.expires>Date.now()/1000&&(!r.burnAt||r.burnAt>Date.now())));},1000);return()=>clearInterval(t);},[]);
  useEffect(()=>{if(log.current&&before===0)log.current.scrollTop=log.current.scrollHeight;},[records.length,before]);
  async function browserLock(id:number){
    if(!navigator.locks)throw new Error('浏览器不支持安全的设备状态锁，请使用新版浏览器。');
    await new Promise<void>((resolve,reject)=>{void navigator.locks.request(`webts-olm-${id}`,{ifAvailable:true},async l=>{if(!l){reject(new Error('另一标签页正在处理加密私信，请先在那一页锁定私信。'));return;}await new Promise<void>(done=>{localRelease.current=done;resolve();});}).catch(reject);});
  }
  async function unlock(create:boolean){if(!me||operation.current)return;operation.current=true;setBusy(true);setStatus('');let state:Unlocked|undefined;
    try{await browserLock(me.id);let identity=backup;
      if(create){if(passphrase!==confirm)throw new Error('两次密钥口令不同');identity=await createIdentity(me.id,passphrase);await saveLocal('keys',`identity:${me.id}`,identity);setBackup(identity);await api('/friends/key',{password,public_key:identity.publicKey});download(identity);}
      if(!identity)throw new Error('请先导入私信身份备份');const own=await api<Me>('/friends/me');setMe(own);
      if(!own.public_key){await api('/friends/key',{password,public_key:identity.publicKey});own.public_key=identity.publicKey;}
      const local=await loadLocal<Encrypted>('keys',`state:${me.id}`);state=await unlockState(identity,local,me.id,own.public_key,passphrase);
      const pre=JSON.parse(state.engine.prekeys());await persist(state);
      await api('/friends/device',{password,lease:state.saved.lease,device:state.saved.device,...pre});
      if(!alive.current){state.engine.free();localRelease.current?.();return;}
      engine.current=state;setUnlocked(true);setShowKeys(false);setStatus('此设备已解锁。私钥、棘轮状态和本地缓存仅以口令加密形式保存。');await flushOutbox(state);await refresh();
    }catch(e){if(state&&engine.current===state){dispose();setUnlocked(false);}else{state?.engine.free();localRelease.current?.();localRelease.current=undefined;}setStatus(e instanceof Error?e.message:'解锁失败');}finally{setPassphrase('');setConfirm('');setPassword('');setBusy(false);finishOperation();}
  }
  async function importIdentity(file:File){try{if(!me||file.size>128*1024)throw new Error('请选择128KiB以内的身份备份');const value:Encrypted=JSON.parse(await file.text());if(value.account!==me.id||value.version!==1||value.kind!=='identity')throw new Error('备份不属于当前账号或版本不支持');if(me.public_key&&value.publicKey!==me.public_key)throw new Error('备份与登记公钥不一致');await saveLocal('keys',`identity:${me.id}`,value);setBackup(value);setStatus('已导入受口令保护的私信身份，请解锁。新设备只能读取发给新设备的后续消息。');}catch(e){setStatus(e instanceof Error?e.message:'导入失败');}}
  async function friendship(id:number,action:string){setBusy(true);try{await api(`/friends/${id}`,{action});if(id===selected){setSelected(undefined);setRecords([]);}await refresh();}catch(e){setStatus(e instanceof Error?e.message:'操作失败');}finally{setBusy(false);}}
  async function flushOutbox(state:Unlocked){const pending=state.saved.outbox;if(!pending)return;await privateApi(state,'/messages',pending);delete state.saved.outbox;await persist(state);}
  async function send(sticker?:string){if(!me||!peer||!trusted||!engine.current||operation.current)return;if(!draft.trim()&&!image&&!sticker)return;operation.current=true;setBusy(true);setStatus('');const state=engine.current;let snapshot=state.engine.save();let savedSnapshot=structuredClone(state.saved);let stored=false;
    try{if(!me.storage_enabled)throw new Error('管理员尚未配置私有对象存储；不会发送明文。');await flushOutbox(state);snapshot=state.engine.save();savedSnapshot=structuredClone(state.saved);const root=JSON.parse(peer.public_key);
      if(!state.engine.has_session(root.curve)||state.saved.peerDevices[peer.id]!==peer.device){const claimed=await privateApi<{key:string;bundle:{payload:string;signature:string;device:string}}>(state,`/${peer.id}/prekey`,{});const target=await checkPrekey(peer.public_key,claimed);state.engine.outbound(target.curve,claimed.key);state.saved.peerDevices[peer.id]=target.device;}
      const id=crypto.randomUUID(),value:Envelope={version:1,site:location.origin,id,sender:me.id,recipient:peer.id,expires:Math.floor(Date.now()/1000)+me.retention_days*86400,text:draft,image:image||undefined,sticker,burn};
      const ciphertext=await sealMessage(value,state,root.curve,state.saved.peerDevices[peer.id]);state.saved.outbox={peer:peer.id,id,ciphertext,burn};if(!burn)state.saved.cache[id]={value,created_at:Date.now()/1000};await persist(state);stored=true;setDraft('');setImage('');
      await flushOutbox(state);setStatus(burn?'阅后即焚密文已发送，对方成功解密后服务器开始删除。':'加密私信已送达');
    }catch(e){if(!stored&&alive.current&&engine.current===state){const m=await cryptoModule();state.engine.free();state.engine=m.Engine.restore(snapshot);state.saved=savedSnapshot;}setStatus(`${e instanceof Error?e.message:'发送失败'}${stored?'；密文已保留在本机待发箱，点击重试将发送同一份密文。':''}`);}finally{setBusy(false);finishOperation();}
    if(stored)void receive().catch(e=>setStatus(e.message));
  }
  async function receive(){const state=engine.current;if(!state||!me||!peer||operation.current||!trusted)return;operation.current=true;const target=peer.id;
    try{const display:Display[]=[];
      for(const id of state.saved.readPending??[]){try{await privateApi(state,`/messages/${id}/read`,{});state.saved.readPending=state.saved.readPending?.filter(v=>v!==id);await persist(state);}catch(e){if((e as {status?:number}).status===404){state.saved.readPending=state.saved.readPending?.filter(v=>v!==id);await persist(state);}}}
      const data=await privateApi<{messages:Message[]}>(state,`/${target}/messages${before?`?before=${before}`:''}`);
      for(const row of [...data.messages].reverse()){
        if(!alive.current||selectedRef.current!==target||engine.current!==state)return;const cached=state.saved.cache[row.id];if(row.burn&&recordsRef.current.some(r=>r.id===row.id&&r.value))continue;
        if(cached&&!row.burn){display.push({...row,value:cached.value});continue;}
        if(row.sender===me.id){display.push({...row,error:row.burn?'阅后即焚消息不保留本地正文':'本机没有此消息的历史缓存'});continue;}
        const snapshot=state.engine.save();let durable=false;
        try{const result=await privateApi<{ciphertext:string}>(state,`/messages/${row.id}`);if(!alive.current||engine.current!==state||selectedRef.current!==target)return;const value=await openMessage(result.ciphertext,state,JSON.parse(peer.public_key).curve,{site:location.origin,id:row.id,sender:row.sender,recipient:row.recipient,burn:row.burn});value.expires=Math.min(value.expires,row.expires);if(value.expires<=Date.now()/1000)throw new Error('消息已过期');
          if(!row.burn)state.saved.cache[row.id]={value,created_at:row.created_at};state.saved.readPending=[...(state.saved.readPending??[]).filter(v=>v!==row.id),row.id];await persist(state);durable=true;
          // Acknowledge only after authentication, decryption and durable ratchet state saving.
          try{await privateApi(state,`/messages/${row.id}/read`,{});state.saved.readPending=state.saved.readPending?.filter(v=>v!==row.id);await persist(state);}catch{setStatus('消息已安全解密，已读 / 焚毁确认等待重试。');}display.push({...row,value,burnAt:row.burn?Date.now()+60000:undefined});
        }catch(e){if(!alive.current||engine.current!==state)return;if(!durable){const m=await cryptoModule();state.engine.free();state.engine=m.Engine.restore(snapshot);delete state.saved.cache[row.id];state.saved.readPending=state.saved.readPending?.filter(v=>v!==row.id);}display.push({...row,error:e instanceof Error?e.message:'消息解密失败'});}
      }
      if(alive.current&&selectedRef.current===target){setRecords(old=>{const liveBurn=old.filter(r=>r.burnAt&&r.burnAt>Date.now());return [...display.filter(r=>!liveBurn.some(b=>b.id===r.id)),...liveBurn].sort((a,b)=>a.seq-b.seq);});}await refresh();
    }finally{finishOperation();}
  }
  const content=<section className={`friends-layout ${peer||showKeys?'show-conversation':''}`} aria-label="好友与端到端加密私信">
    <aside className="friends-list"><header><div><small>WEBTS FRIENDS</small><h2>好友</h2></div><button className="icon-button" aria-label="关闭好友" onClick={close}>×</button></header><p className="muted">无需连接 TS 服务器。原生 TS 私聊在语音空间中独立使用。</p>
      {me&&<div className="friend-code"><small>我的好友码</small><code>{me.code}</code><button className="text-button" onClick={()=>navigator.clipboard.writeText(me.code).then(()=>setStatus('好友码已复制')).catch(()=>setStatus('请手动复制好友码'))}>复制</button></div>}
      <form onSubmit={async e=>{e.preventDefault();setBusy(true);try{await api('/friends/request',{code:code.trim()});setCode('');await refresh();setStatus('请求已发送，对方接受后可核对安全码。');}catch(e){setStatus(e instanceof Error?e.message:'添加失败');}finally{setBusy(false);}}}><label>添加好友<input value={code} onChange={e=>setCode(e.target.value)} placeholder="粘贴对方好友码" maxLength={24} required/></label><button className="secondary full" disabled={busy||!me?.public_key}>发送好友请求</button></form>
      <div className="friend-rows">{friends.filter(f=>f.status===1).map(f=><button className={`friend-row ${f.id===selected?'active':''}`} key={f.id} onClick={()=>setSelected(f.id)}><span className="avatar">{title(f).slice(0,1)}</span><span><strong>{title(f)}</strong><small>双棘轮 · 加密私信</small></span><span>›</span></button>)}{friends.filter(f=>f.status!==1).map(f=><article className="friend-request" key={f.id}><strong>{title(f)}</strong><small>{f.status===2?'已屏蔽':f.requester===me?.id?'等待对方接受':'请求添加你为好友'}</small><div>{f.status===0&&f.requester!==me?.id&&<button disabled={busy} className="text-button" onClick={()=>friendship(f.id,'accept')}>接受</button>}<button disabled={busy||f.status===2&&f.blocked_by!==me?.id} className="text-button" onClick={()=>friendship(f.id,f.status===2?'unblock':'decline')}>{f.status===2?'解除屏蔽':'取消 / 拒绝'}</button></div></article>)}</div>
      {!unlocked&&<button className="primary full" onClick={()=>setShowKeys(true)}>配置 / 解锁私信</button>}
      {unlocked&&<button className="secondary full" onClick={lock} disabled={busy}>锁定本机私信</button>}
    </aside>
    <section className="friend-conversation"><header className="friend-heading"><button className="friend-back" onClick={()=>{setSelected(undefined);setShowKeys(false);}} aria-label="返回好友列表">‹</button><div><small>OLM DOUBLE RATCHET · 实验支持</small><h2>{peer?title(peer):'只有你和好友能读取的对话'}</h2></div>{peer&&<button className="text-button danger" disabled={busy} onClick={()=>{if(window.confirm(`屏蔽 ${title(peer)} 并清理双方临时消息？`))void friendship(peer.id,'block');}}>屏蔽</button>}</header>
      {status&&<p className="friend-status" role="status">{status}</p>}
      {!unlocked?<div className="friend-key-setup"><h3>{me?.public_key?'解锁私信身份':'创建你的私信身份'}</h3><p>设备私钥使用独立口令加密保存在此浏览器。网站无法替你解密，忘记口令或遗失备份不能通过邮箱找回。</p><p>一次一台设备处理双棘轮私信；从备份在新设备接管时，旧临时消息会过期；只能收到后续消息，旧设备停止私信。语音和 TS 聊天不受影响。</p>
        <label>私信密钥口令<input type="password" value={passphrase} autoComplete="off" onChange={e=>setPassphrase(e.target.value)} minLength={16} maxLength={256}/></label>{!me?.public_key&&!backup&&<label>再次输入密钥口令<input type="password" autoComplete="off" value={confirm} onChange={e=>setConfirm(e.target.value)}/></label>}
        <label>当前网站账号密码（确认设备接管）<input type="password" autoComplete="current-password" value={password} onChange={e=>setPassword(e.target.value)}/></label><button className="primary full" disabled={busy||!password||!passphrase||!!me?.public_key&&!backup} onClick={()=>unlock(!me?.public_key&&!backup)}>{busy?'正在处理…':me?.public_key||backup?'解锁并接管此设备':'创建、下载备份并解锁'}</button>
        <label className="secondary file-button">导入私信身份备份<input type="file" accept="application/json,.json" disabled={busy} onChange={e=>{const f=e.target.files?.[0];e.target.value='';if(f)void importIdentity(f);}}/></label>{backup&&<button className="text-button" onClick={()=>download(backup)}>重新下载受口令保护的身份备份</button>}
      </div>:peer?<><section className="friend-safety"><div><strong>{trusted?'已核对好友身份':'核对安全码后开始聊天'}</strong><small>请通过当面或另一可信渠道与对方核对，双方代码应完全一致。</small><code>{safety||'正在计算…'}</code></div>{!trusted&&<><label className="checkbox"><input type="checkbox" checked={confirmTrust} onChange={e=>setConfirmTrust(e.target.checked)}/>我已与好友核对安全码一致</label><button className="secondary small" disabled={!confirmTrust||!safety} onClick={async()=>{if(!me)return;await saveLocal('trust',`${me.id}:${peer.id}`,peer.public_key);setTrusted(true);setStatus('好友身份已固定在此设备。');}}>信任此身份</button></>}</section>
        <div className="friend-messages" ref={log} role="log" aria-label="端到端私信消息">{records.length>=30&&<button className="text-button" disabled={busy} onClick={()=>setBefore(records[0].seq)}>更早的临时消息</button>}{before>0&&<button className="text-button" onClick={()=>setBefore(0)}>返回最新消息</button>}{records.length===0&&<div className="chat-empty"><span className="friend-lock">♢</span><p>{trusted?'开始一段加密对话':'安全码核对前不会解密或发送消息'}</p><small>默认 {me?.retention_days??7} 天后过期 · 临时图片一并加密</small></div>}{records.map(row=><article className={`friend-message ${row.sender===me?.id?'self':''}`} key={row.id}><small>{row.sender===me?.id?'你':title(peer)} · {new Date(row.created_at*1000).toLocaleTimeString([], {hour:'2-digit',minute:'2-digit'})}{row.burn?' · 阅后即焚':''}</small>{row.value?<><p>{row.value.text}</p>{row.value.image&&<img src={row.value.image} alt="加密聊天图片" loading="lazy"/>}{row.value.sticker&&<Sticker id={row.value.sticker}/>}</>:<p className="muted">{row.error??'等待解密'}</p>}{row.burnAt&&<small>已触发服务器删除，本页将在60秒内隐藏。对方仍可截图或保存。</small>}</article>)}</div>
        {image&&<div className="friend-attachment"><img src={image} alt="待发加密图片"/><button className="text-button danger" onClick={()=>setImage('')}>移除图片</button></div>}
        <div className="friend-compose-options"><label className="checkbox"><input type="checkbox" checked={burn} onChange={e=>setBurn(e.target.checked)}/>阅后即焚</label><label className="text-button file-button">图片 / 自定义表情<input type="file" accept="image/png,image/jpeg,image/webp" disabled={busy||!trusted} onChange={e=>{const file=e.target.files?.[0];e.target.value='';if(file)setCrop(file);}}/></label>{engine.current?.saved.outbox&&<button className="text-button" disabled={busy} onClick={async()=>{const state=engine.current;if(!state||operation.current)return;operation.current=true;setBusy(true);try{await flushOutbox(state);setStatus('待发密文已送达');}catch(e){setStatus(e instanceof Error?e.message:'重试失败');}finally{finishOperation();setBusy(false);}}}>重试待发消息</button>}{engine.current?.saved.outbox&&<button className="text-button danger" disabled={busy} onClick={async()=>{const state=engine.current;if(!state||operation.current||!window.confirm("放弃待发消息？若服务器已收到，它仍可能送达；此操作不会撤回。"))return;operation.current=true;setBusy(true);try{delete state.saved.outbox;await persist(state);setStatus("待发密文已放弃，棘轮状态已保留。");}catch(e){setStatus(e instanceof Error?e.message:"保存失败");}finally{finishOperation();setBusy(false);}}}>放弃待发消息</button>}</div>
        <form className="composer friend-composer" onSubmit={e=>{e.preventDefault();void send();}}><StickerPicker emoji={t=>setDraft(v=>(v+t).slice(0,4096))} sticker={id=>{void send(id);}}/><input aria-label="好友加密私信内容" value={draft} onChange={e=>setDraft(e.target.value)} maxLength={4096} disabled={!trusted||busy} placeholder={trusted?'发送端到端加密私信…':'先核对安全码'}/><button disabled={!trusted||busy||!me?.storage_enabled||!draft.trim()&&!image} aria-label="发送加密私信">➜</button></form>
      </>:<div className="chat-empty"><span className="friend-lock">♢</span><p>选择好友，核对安全码后开始聊天</p><small>成熟 Olm 双棘轮 · 与 Signal 协议不同<br/>手机与电脑都能使用；密文临时保存至私有对象存储。</small></div>}
    </section>
  </section>;
  return <>{inline&&open?<div className="friends-mobile-page">{content}</div>:<dialog ref={dialog} className="friends-dialog" aria-label="WebTS 好友与加密私信" onCancel={e=>{e.preventDefault();close();}}>{open&&content}</dialog>}{crop&&<ImageCropper file={crop} purpose="content" onCancel={()=>setCrop(undefined)} onComplete={value=>{setImage(value);setCrop(undefined);}}/>}</>;
}
