import {useEffect,useRef,useState} from 'react';
import {api} from './api';
export type NoticeSummary={id:number;title:string;created_at:number;read:boolean};
type NoticeDetail={id:number;title:string;created_at:number;html:string};
type InboxPage={items:NoticeSummary[];unread:number;email_enabled:boolean};
// Only server-sanitized HTML is rendered. External images stay explicit links.
export function noticeDisplayHtml(html:string){return html.replace(/<img\b[^>]*>/gi,tag=>{const src=tag.match(/\bsrc="([^"]*)"/i)?.[1];return src?.startsWith('https://')?`<p><a href="${src}" target="_blank" rel="noopener noreferrer nofollow">查看外部图片 ↗</a></p>`:tag;});}
export function NoticeContent({html}:{html:string}){return <article className="notice-content" dangerouslySetInnerHTML={{__html:noticeDisplayHtml(html)}}/>;}
const date=(value:number)=>new Date(value*1000).toLocaleString('zh-CN');
export function Inbox({onNew}:{onNew:()=>void}){
  const[open,setOpen]=useState(false),[items,setItems]=useState<NoticeSummary[]>([]),[unread,setUnread]=useState(0),[enabled,setEnabled]=useState(false),[before,setBefore]=useState(0),[detail,setDetail]=useState<NoticeDetail|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false);
  const dialog=useRef<HTMLDialogElement>(null),latest=useRef<number|undefined>(undefined),callback=useRef(onNew),generation=useRef(0);callback.current=onNew;
  useEffect(()=>{let active=true,inFlight=false;async function refresh(){if(inFlight||document.hidden)return;inFlight=true;try{const data=await api<InboxPage>('/notices');if(!active)return;setUnread(data.unread);setEnabled(data.email_enabled);if(!before)setItems(data.items);const id=data.items[0]?.id??0;if(latest.current!==undefined&&id>latest.current&&data.items.some(n=>n.id>latest.current!&&!n.read))callback.current();latest.current=id;setError('');}catch(e){if(active)setError(e instanceof Error?e.message:'无法读取信件');}finally{inFlight=false;}}void refresh();const timer=window.setInterval(refresh,20000);window.addEventListener('focus',refresh);document.addEventListener('visibilitychange',refresh);return()=>{active=false;clearInterval(timer);window.removeEventListener('focus',refresh);document.removeEventListener('visibilitychange',refresh);};},[before]);
  useEffect(()=>{if(open)dialog.current?.showModal();return()=>dialog.current?.close();},[open]);
  useEffect(()=>()=>{generation.current++;},[]);
  async function read(id:number){const run=++generation.current;setBusy(true);setError('');try{const data=await api<NoticeDetail>(`/notices/${id}`,{});if(run!==generation.current)return;setDetail(data);setItems(v=>v.map(n=>n.id===id?{...n,read:true}:n));const summary=await api<InboxPage>('/notices');if(run===generation.current)setUnread(summary.unread);}catch(e){if(run===generation.current)setError(e instanceof Error?e.message:'读取失败');}finally{if(run===generation.current)setBusy(false);}}
  async function older(){const run=++generation.current;setBusy(true);try{const cursor=items.at(-1)?.id??0;const data=await api<InboxPage>(`/notices?before=${cursor}`);if(run===generation.current){setBefore(cursor);setItems(data.items);}}catch(e){if(run===generation.current)setError(e instanceof Error?e.message:'读取失败');}finally{if(run===generation.current)setBusy(false);}}
  async function preference(value:boolean){const run=++generation.current;setBusy(true);try{await api('/notices/preferences',{email_enabled:value});if(run===generation.current)setEnabled(value);}catch(e){if(run===generation.current)setError(e instanceof Error?e.message:'保存失败');}finally{if(run===generation.current)setBusy(false);}}
  function close(){generation.current++;setOpen(false);setBusy(false);}
  return <><button className={`icon-button inbox-button ${unread?'has-mail':''}`} aria-label={`站点信箱${unread?`，${unread}封未读`:''}`} title="站点信件与更新通知" onClick={()=>{setOpen(true);setDetail(null);}}><svg width="22" height="22" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.8" aria-hidden="true"><rect x="3" y="5" width="18" height="14" rx="3"/><path d="m3 6 9 7 9-7"/></svg>{unread>0&&<span className="inbox-badge">{unread>99?'99+':unread}</span>}</button>{open&&<dialog ref={dialog} className="inbox-dialog" onCancel={close} onClick={e=>{if(e.target===e.currentTarget)close();}}><div className="dialog-head"><h2>站点信箱 <small>{unread} 封未读</small></h2><button className="icon-button" aria-label="关闭信箱" onClick={close}>×</button></div>{error&&<p className="auth-error" role="status">{error}</p>}<label className="checkbox inbox-preference"><input type="checkbox" checked={enabled} disabled={busy} onChange={e=>preference(e.target.checked)}/>同时接收管理员的更新邮件（默认关闭）</label><div className="inbox-layout"><nav className="inbox-list" aria-label="信件列表">{items.length?items.map(n=><button key={n.id} className={`letter-row ${detail?.id===n.id?'active':''} ${!n.read?'unread':''}`} disabled={busy} onClick={()=>read(n.id)}><strong>{!n.read&&<span aria-label="未读">● </span>}{n.title}</strong><time>{date(n.created_at)}</time></button>):<p className="muted">这里还没有信件。</p>}{items.length===50&&<button className="text-button" disabled={busy} onClick={older}>更早的信件</button>}{before>0&&<button className="text-button" onClick={()=>setBefore(0)}>返回最新信件</button>}</nav><section className="letter-reading" aria-label="信件正文">{detail?<><h3>{detail.title}</h3><time>{date(detail.created_at)}</time><NoticeContent html={detail.html}/></>:<div className="chat-empty"><p>选择一封信件</p><small>更新、维护公告与站点消息会出现在这里。</small></div>}</section></div></dialog>}</>;
}
