import {createRoot} from 'react-dom/client';
import {useEffect, useRef, useState} from 'react';
import type {FormEvent,ReactNode} from 'react';
import {api} from './api';
import type {Identity,Member,Channel,State} from './api';
import {Voice} from './voice';
import './style.css';
import {AdminSettings} from './AdminSettings';

type Chat={key:number; name:string; text:string; scope:string; from?:number; target?:number; time:string};
function Icon({name}:{name:string}){const paths:Record<string,ReactNode>={wave:<><path d="M4 10v4m4-8v12m4-15v18m4-15v12m4-8v4"/></>,mic:<><rect x="9" y="2" width="6" height="13" rx="3"/><path d="M5 10v2a7 7 0 0014 0v-2M12 19v3m-4 0h8"/></>,headphones:<><path d="M3 14v-3a9 9 0 0118 0v3"/><rect x="2" y="12" width="5" height="9" rx="2"/><rect x="17" y="12" width="5" height="9" rx="2"/></>,shield:<><path d="M12 2l9 4v6c0 5-9 10-9 10S3 17 3 12V6l9-4zM8 12l3 3 5-6"/></>,hash:<path d="M5 9h16M3 15h16M10 3L6 21M18 3l-4 18"/>,users:<><circle cx="9" cy="8" r="4"/><path d="M1 21v-2a7 7 0 0114 0v2m1-16a4 4 0 010 7m3 9v-2a6 6 0 00-3-5"/></>,arrow:<path d="M3 12h18m-7-7l7 7-7 7"/>,settings:<><circle cx="12" cy="12" r="3"/><path d="M12 2v3m0 14v3M2 12h3m14 0h3M5 5l2 2m10 10l2 2M5 19l2-2M17 7l2-2"/></>,sun:<><circle cx="12" cy="12" r="4"/><path d="M12 1v3m0 16v3M1 12h3m16 0h3M4 4l2 2m12 12l2 2M4 20l2-2M18 6l2-2"/></>,close:<path d="M6 6l12 12M6 18L18 6"/>,plus:<path d="M12 4v16M4 12h16"/>,exit:<path d="M10 3H3v18h7m5-14l5 5-5 5m-7-5h12"/>,lock:<><rect x="5" y="10" width="14" height="12" rx="2"/><path d="M8 10V6a4 4 0 018 0v4"/></>};return <svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.6" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true">{paths[name]??paths.hash}</svg>;}
function Modal({title,close,children}:{title:string;close:()=>void;children:ReactNode}){const ref=useRef<HTMLDialogElement>(null);useEffect(()=>{ref.current?.showModal();return()=>ref.current?.close();},[]);return <dialog ref={ref} onCancel={close} onClick={e=>{if(e.target===e.currentTarget)close();}}><div className="dialog-head"><h2>{title}</h2><button className="icon-button" aria-label="关闭" onClick={close}><Icon name="close"/></button></div>{children}</dialog>;}
function App(){
  const[user,setUser]=useState<{email:string;is_admin?:boolean}|null>(null);const[loaded,setLoaded]=useState(false);const[identities,setIdentities]=useState<Identity[]>([]);const[servers,setServers]=useState<{id:string;name:string}[]>([]);const[identity,setIdentity]=useState('');const[server,setServer]=useState('');const[state,setState]=useState<State|null>(null);const[selected,setSelected]=useState<number>();const[status,setStatus]=useState('尚未连接');const[connected,setConnected]=useState(false);const[busy,setBusy]=useState(false);const[notice,setNotice]=useState('');const[modal,setModal]=useState('');const[auth,setAuth]=useState('login');const[chat,setChat]=useState<Chat[]>([]);const[scope,setScope]=useState('channel');const[message,setMessage]=useState('');const[muted,setMuted]=useState(false);const[deafened,setDeafened]=useState(false);const[mode,setMode]=useState<'ptt'|'open'>('open');const[transmitting,setTransmitting]=useState(false);const[level,setLevel]=useState(0);const[cipher,setCipher]=useState('');const[devices,setDevices]=useState<MediaDeviceInfo[]>([]);const[input,setInput]=useState('');const[output,setOutput]=useState('');const[speaking,setSpeaking]=useState<Record<number,number>>({});const[volumes,setVolumes]=useState<Record<number,number>>({});const[theme,setTheme]=useState(()=>localStorage.getItem('webts-theme')??'dark');const[mobile,setMobile]=useState('chat');const[token,setToken]=useState('');const[authEmail,setAuthEmail]=useState('');const[authError,setAuthError]=useState('');const[authResult,setAuthResult]=useState<{kind:string;success:boolean;message:string}|null>(null);
  const[allowCustom,setAllowCustom]=useState(false);const[customAddress,setCustomAddress]=useState('');
  const voice=useRef<Voice|null>(null);const page=useRef(crypto.randomUUID());const last=useRef<HTMLDivElement>(null);const pending=useRef(new Map<string,()=>void>());
  if(!voice.current)voice.current=new Voice(e=>{switch(e.type){case 'state':setState(e as unknown as State);setConnected(true);setStatus('已连接');break;case 'status':setStatus(String(e.message));break;case 'error':case 'notice':setNotice(String(e.message));break;case 'disconnected':setConnected(false);setTransmitting(false);setLevel(0);setBusy(false);setState(null);setCipher('');setStatus('尚未连接');pending.current.clear();break;case 'encryption':setCipher(String(e.browser).replace('SRTP_AEAD_','').replaceAll('_','-'));break;case 'speaking':setSpeaking(v=>({...v,[Number(e.client)]:Date.now()}));break;case 'transmit':setTransmitting(Boolean(e.enabled));break;case 'level':setLevel(Number(e.level));break;case 'chat':case 'poke':setChat(v=>[...v.slice(-499),{key:Date.now()+Math.random(),name:String(e.name),text:(e.type==='poke'?'戳了戳你：':'')+String(e.text??''),scope:String(e.scope??'system'),from:Number(e.from),target:e.target==null?undefined:Number(e.target),time:new Date().toLocaleTimeString('zh-CN',{hour:'2-digit',minute:'2-digit'})}]);break;case 'result':if(e.ok){pending.current.get(String(e.id))?.();}else setNotice(String(e.message??'操作被服务器拒绝'));pending.current.delete(String(e.id));break;}});
  async function refresh(){const data=await api<{identities:Identity[]}>('/identities');setIdentities(data.identities);setIdentity(old=>data.identities.some(i=>i.id===old)?old:(data.identities.find(i=>i.is_default)?.id??data.identities[0]?.id??''));await refreshServers();}
  async function refreshServers(){const targets=await api<{servers:{id:string;name:string}[];default_server:string;allow_custom:boolean}>('/servers');setServers(targets.servers);setAllowCustom(targets.allow_custom);setServer(old=>targets.servers.some(s=>s.id===old)||old==='$custom'&&targets.allow_custom?old:targets.default_server||(targets.servers.length===0&&targets.allow_custom?'$custom':''));}
  useEffect(()=>{if(!user)return;const focus=()=>{refreshServers().catch(()=>{});};window.addEventListener('focus',focus);return()=>window.removeEventListener('focus',focus);},[user]);
  useEffect(()=>{api<{user:{email:string;is_admin?:boolean}}>('/me').then(async d=>{setUser(d.user);await refresh();}).catch(()=>{}).finally(()=>setLoaded(true));const readLink=()=>{const hash=new URLSearchParams(location.hash.slice(1));for(const kind of ['verify','reset']){const value=hash.get(kind);if(value){history.replaceState(null,'',location.pathname);setToken(value);setAuth(kind);setAuthResult(null);setAuthError('');setModal('auth');break;}}};readLink();window.addEventListener('hashchange',readLink);return()=>{window.removeEventListener('hashchange',readLink);voice.current?.close();};},[]);
  useEffect(()=>{document.documentElement.dataset.theme=theme;localStorage.setItem('webts-theme',theme);},[theme]);
  useEffect(()=>{const interval=window.setInterval(()=>setSpeaking(v=>{const next=Object.fromEntries(Object.entries(v).filter(([,t])=>Date.now()-t<700));return Object.keys(next).length===Object.keys(v).length?v:next;}),250);return()=>clearInterval(interval);},[]);
  useEffect(()=>{last.current?.scrollIntoView({block:'nearest'});},[chat,scope]);
  useEffect(()=>{const key=(e:KeyboardEvent)=>{if(e.code!=='Space'||mode!=='ptt'||!connected||e.target instanceof HTMLInputElement||e.target instanceof HTMLTextAreaElement||e.target instanceof HTMLSelectElement||e.target instanceof HTMLButtonElement)return;e.preventDefault();voice.current?.press(e.type==='keydown');};const release=()=>voice.current?.press(false);window.addEventListener('keydown',key);window.addEventListener('keyup',key);window.addEventListener('blur',release);document.addEventListener('visibilitychange',release);return()=>{window.removeEventListener('keydown',key);window.removeEventListener('keyup',key);window.removeEventListener('blur',release);document.removeEventListener('visibilitychange',release);};},[mode,connected]);
  async function perform(action:()=>Promise<void>){setBusy(true);try{await action();}catch(e){setNotice(e instanceof Error?e.message:'操作失败');}finally{setBusy(false);}}
  function command(action:string,data:Record<string,unknown>,onSuccess?:()=>void){const id=crypto.randomUUID();if(onSuccess)pending.current.set(id,onSuccess);voice.current?.send({type:'command',id,action,...data});}
  function disconnect(){voice.current?.close();setConnected(false);setState(null);setStatus('尚未连接');setCipher('');setTransmitting(false);pending.current.clear();}
  const member=state?.members.find(m=>m.id===selected);const own=state?.members.find(m=>m.id===state.own);const channel=state?.channels.find(c=>c.id===own?.channel);const activeIdentity=identities.find(i=>i.id===identity);const visibleChats=chat.filter(c=>c.scope==='system'||c.scope===scope||scope==='private'&&c.scope==='client'&&(c.from===selected||c.target===selected));
  const nicknameCharacters=Array.from((activeIdentity?.name??'WebTS').trim()).slice(0,30);const defaultNickname=nicknameCharacters.length<3?`${nicknameCharacters.join('')} · WebTS`:nicknameCharacters.join('');
  async function connection(e:FormEvent<HTMLFormElement>){e.preventDefault();const data=new FormData(e.currentTarget);setModal('');setBusy(true);try{setStatus(data.get('listen')==='on'?'正在连接服务器…':'正在打开麦克风…');await voice.current!.connect({server:server==='$custom'?'':server,...(server==='$custom'?{address:customAddress.trim()}:{}),identity,page:page.current,name:data.get('name'),password:data.get('password')},input,data.get('listen')==='on');navigator.mediaDevices?.enumerateDevices().then(setDevices).catch(()=>{});}catch(e){disconnect();setNotice(e instanceof Error?e.message:'连接失败');}finally{setBusy(false);}}
  function authView(kind:string){setAuth(kind);setAuthResult(null);setAuthError('');setNotice('');}
  async function authenticate(e:FormEvent<HTMLFormElement>){
    e.preventDefault();const data=new FormData(e.currentTarget);
    if(auth==='reset'&&data.get('password')!==data.get('confirm')){setAuthError('两次输入的密码不同，请重新确认。');return;}
    setBusy(true);setNotice('');setAuthError('');
    try{
      if(auth==='login'){const d=await api<{user:{email:string;is_admin?:boolean}}>('/auth/login',{email:data.get('email'),password:data.get('password'),remember:data.get('remember')==='on'});setUser(d.user);await refresh();setModal('');setAuthResult(null);}
      else{
        if(data.get('email'))setAuthEmail(String(data.get('email')));
        const body=auth==='verify'?{token}:auth==='reset'?{token,password:data.get('password')}:['forgot','resend'].includes(auth)?{email:data.get('email')}:{email:data.get('email'),password:data.get('password')};
        const d=await api<{message:string}>(`/auth/${auth}`,body);setAuthResult({kind:auth,success:true,message:d.message});setToken('');
      }
    }catch(e){const message=e instanceof Error?e.message:'操作暂时无法完成';if(['verify','reset'].includes(auth))setAuthResult({kind:auth,success:false,message});else setAuthError(message);}
    finally{setBusy(false);}
  }
  async function exportIdentity(i:Identity){const password=prompt('请输入当前账号密码，以确认导出身份。');if(password===null)return;await perform(async()=>{const r=await fetch(`/api/identities/${i.id}/export`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({password})});if(!r.ok)throw new Error((await r.json()).error);const url=URL.createObjectURL(await r.blob());const a=document.createElement('a');a.href=url;a.download='teamspeak-identity.ini';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);});}
  function move(c:Channel){const password=c.password?prompt(`进入「${c.name}」的频道密码`):'';if(password!==null)command('move',{channel:c.id,password});}
  function tree(parent=0,seen=new Set<number>(),depth=0):ReactNode{if(depth>20)return null;return state?.channels.filter(c=>c.parent===parent&&!seen.has(c.id)).sort((a,b)=>a.order-b.order||a.id-b.id).map(c=>{const path=new Set(seen);path.add(c.id);const members=state.members.filter(m=>m.channel===c.id);return <div key={c.id} style={{paddingLeft:depth?12:0}}><button className={`channel ${own?.channel===c.id?'active':''}`} onDoubleClick={()=>move(c)} onClick={()=>setNotice(c.topic??'双击频道进入；频道操作使用顶部菜单。')}><Icon name={c.password?'lock':'hash'}/><span>{c.name}</span><small>{members.length}</small></button>{members.map(m=><button key={m.id} className={`member-row ${selected===m.id?'selected':''}`} onClick={()=>{setSelected(m.id);setMobile('members');}}><span className={`avatar tiny ${speaking[m.id]?'talking':''}`}>{m.name.slice(0,1)}</span><span>{m.name}{m.id===state.own&&<small> 你</small>}</span>{(m.muted||m.deafened)&&<Icon name={m.deafened?'headphones':'mic'}/>}</button>)}{tree(c.id,path,depth+1)}</div>;});}
  return <div className="app">
    <header className="topbar"><a className="brand" href="/" aria-label="WebTS 首页"><span className="brand-mark"><Icon name="wave"/></span><strong>Web<span>TS</span></strong><span className="brand-note">让声音相聚</span></a><div className="top-actions"><span className="version">PREVIEW · 0.1</span>{user?.is_admin&&<button className="icon-button" aria-label="站点管理" onClick={()=>setModal('admin')}><Icon name="settings"/></button>}<button className="icon-button" aria-label="切换深浅主题" onClick={()=>setTheme(theme==='dark'?'light':'dark')}><Icon name="sun"/></button>{user?<button className="account-button" onClick={()=>setModal('account')}><span className="avatar mini">{user.email[0].toUpperCase()}</span><span>{user.email}</span></button>:<button className="primary small" disabled={!loaded} onClick={()=>{authView('login');setModal('auth');}}>登录 / 注册 <Icon name="arrow"/></button>}</div></header>
    <nav className="mobile-tabs" aria-label="主面板">{[['channels','频道'],['chat','聊天'],['members','成员']].map(([id,label])=><button key={id} className={mobile===id?'active':''} onClick={()=>setMobile(id)}>{label}</button>)}</nav>
    {notice&&<div className="notice" role="status"><span>{notice}</span><button className="icon-button" aria-label="关闭提示" onClick={()=>setNotice('')}><Icon name="close"/></button></div>}
    <main className={`workspace mobile-${mobile}`}>
      <aside className="sidebar channels-panel"><div className="panel-heading"><span>你的空间</span><span className="eyebrow">TEAM SPEAK</span></div><div className="server-card"><span className="server-mark"><Icon name="wave"/></span><div><strong>{state?.server??'连接你的服务器'}</strong><p><span className={`dot ${connected?'online':''}`}/>{status}</p></div></div>
      <div className="selectors"><label>服务器<select value={server} disabled={connected} onChange={e=>setServer(e.target.value)}><option value="">{user?'尚未配置服务器':'登录后选择服务器'}</option>{servers.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}{allowCustom&&<option value="$custom">自定义公网地址</option>}</select></label><label>当前身份<button className="text-button" onClick={()=>user?setModal('identities'):setModal('auth')}>管理</button><select value={identity} disabled={connected} onChange={e=>setIdentity(e.target.value)}><option value="">{user?'先创建或导入身份':'身份随账号安全保存'}</option>{identities.map(i=><option key={i.id} value={i.id}>{i.name}{i.is_default?' · 默认':''}</option>)}</select></label></div>
      <div className="section-label">频道列表{connected&&<button className="icon-button" aria-label="创建频道" onClick={()=>setModal('channel_create')}><Icon name="plus"/></button>}</div><div className="channel-list">{state?tree():<div className="empty-list"><Icon name="hash"/><p>频道将在连接后出现</p><small>使用你的真实 TS 身份<br/>继续熟悉的频道与权限</small></div>}</div>
      <div className="connect-area"><button className={connected?'secondary danger':'primary'} disabled={busy||!user||!server||!identity} onClick={()=>connected?disconnect():setModal('connect')}>{connected?<><Icon name="exit"/>断开连接</>:<>连接服务器<Icon name="arrow"/></>}</button><small>{!user?'登录后即可连接':!identity?'创建身份，或导入客户端身份':connected?'切换身份前，请先断开连接':'密码只在建立连接时使用'}</small></div></aside>
      <section className="chat-panel"><div className="chat-heading"><div><div className="eyebrow">{connected?'CHANNEL':'WELCOME TO WEBTS'}</div><h1><Icon name={connected?'hash':'wave'}/>{channel?.name??'每一次相聚，从这里开始'}</h1><p>{channel?.topic??'你熟悉的 TeamSpeak，现在在浏览器里。'}</p></div>{connected&&<button className="icon-button" aria-label="管理当前频道" onClick={()=>setModal('channel_edit')}><Icon name="settings"/></button>}</div>
      {connected?<><div className="chat-tabs">{[['channel','频道聊天'],['server','服务器'],['private','私聊']].map(([id,label])=><button className={scope===id?'active':''} onClick={()=>setScope(id)} key={id}>{label}</button>)}{scope==='private'&&<small>{member?`与 ${member.name}`:'请选择成员'}</small>}</div><div className="messages" role="log" aria-label="聊天消息">{visibleChats.length===0&&<div className="chat-empty"><Icon name="hash"/><p>{scope==='private'?'选择一位成员，开始私聊':'这里是对话的起点'}</p><small>消息由 TeamSpeak 实时传递，网页不会保存聊天历史。</small></div>}{visibleChats.map(c=><div className="chat-message" key={c.key}><span className="avatar">{c.name.slice(0,1)}</span><div><header><strong>{c.name}</strong><time>{c.time}</time>{c.scope==='system'&&<span className="tag">提醒</span>}</header><p>{c.text}</p></div></div>)}<div ref={last}/></div><form className="composer" onSubmit={e=>{e.preventDefault();if(!message.trim()||scope==='private'&&!member)return;const text=message;command('chat',{scope,client:member?.id,text},()=>{setChat(v=>[...v.slice(-499),{key:Date.now()+Math.random(),name:own?.name??'你',text,scope,from:state?.own,target:member?.id,time:new Date().toLocaleTimeString('zh-CN',{hour:'2-digit',minute:'2-digit'})}]);});setMessage('');}}><input aria-label="聊天内容" placeholder={scope==='private'?`私聊 ${member?.name??'请选择成员'}`:`发送消息到 ${scope==='server'?'服务器':channel?.name??'频道'}`} value={message} onChange={e=>setMessage(e.target.value)} maxLength={1024}/><button aria-label="发送消息" disabled={!message.trim()||scope==='private'&&!member}><Icon name="arrow"/></button></form></>:<div className="welcome"><div className="orbit"><div className="orbit-ring"/><div className="orbit-ring second"/><div className="wave-symbol"><Icon name="wave"/></div><span className="orbit-dot one"/><span className="orbit-dot two"/></div><span className="welcome-tag"><span className="dot online"/>属于你的声音空间</span><h2>带上身份，<br/>与伙伴<span>重新相聚。</span></h2><p>无需切换客户端。从一场游戏，到一次闲聊，<br/>你的频道、你的朋友、你的权限，都在这里。</p><div className="welcome-actions"><button className="primary" onClick={()=>user?setModal('identities'):(setAuth('register'),setModal('auth'))}>{user?'管理我的身份':'创建邮箱账号'}<Icon name="arrow"/></button><button className="secondary" onClick={()=>{setModal(user?'identities':'auth');setAuth('login');}}>{user?'导入已有身份':'已有账号？登录'}</button></div><div className="feature-strip"><span><Icon name="shield"/>加密传输</span><span><Icon name="users"/>真实身份权限</span><span><Icon name="headphones"/>Opus 语音</span></div><small className="boundary">语音通过网关转接；网关可访问语音内容。移动语音为试验支持。</small></div>}
      <footer className="voice-bar"><div className={`voice-status ${transmitting?'speaking':''}`}><span className="avatar"><Icon name="mic"/></span><div><strong>{connected&&transmitting?(mode==='open'?'麦克风已开启':'正在发言'):connected?(own?.name??'语音已连接'):'语音待连接'}</strong><small>{connected?(cipher||'正在确认加密套件…'):'WebRTC · DTLS-SRTP'}</small></div></div><div className="voice-controls"><button className={`icon-button ${muted?'off':''}`} disabled={!connected} aria-label={muted?'取消麦克风静音':'麦克风静音'} onClick={()=>{setMuted(!muted);voice.current?.setMute(!muted,deafened);}}><Icon name="mic"/></button><button className={`icon-button ${deafened?'off':''}`} disabled={!connected} aria-label={deafened?'恢复收听':'停止收听'} onClick={()=>{setDeafened(!deafened);voice.current?.setMute(muted,!deafened);}}><Icon name="headphones"/></button><button className="icon-button" aria-label="语音设备设置" onClick={()=>{navigator.mediaDevices?.enumerateDevices().then(setDevices).catch(()=>{});setModal('audio');}}><Icon name="settings"/></button><button className={`ptt ${transmitting?'pressed':''}`} disabled={!connected||muted} onPointerDown={e=>{e.currentTarget.setPointerCapture(e.pointerId);voice.current?.press(true);}} onPointerUp={()=>voice.current?.press(false)} onPointerCancel={()=>voice.current?.press(false)}>{mode==='ptt'?'按住发言':transmitting?'自由发言':'麦克风未发送'}<kbd>{mode==='ptt'?'SPACE':'OPEN'}</kbd></button></div></footer></section>
      <aside className="sidebar details-panel"><div className="panel-heading"><span>成员信息</span><Icon name="users"/></div>{member?<><div className="profile"><span className={`avatar large ${speaking[member.id]?'talking':''}`}>{member.name.slice(0,1)}</span><h2>{member.name}</h2><span className="tag">{member.id===state?.own?'当前身份':'在线成员'}</span></div><dl><dt>所在频道</dt><dd>{state?.channels.find(c=>c.id===member.channel)?.name}</dd><dt>身份 UID</dt><dd className="uid">{member.uid??'服务器未提供'}</dd><dt>服务器组</dt><dd>{member.serverGroups.join(' · ')||'服务器未提供'}</dd><dt>频道组 / 发言权</dt><dd>{member.channelGroup} / {member.talkPower}</dd></dl><p className="member-description">{member.description||'这位成员还没有设置介绍。'}</p><label className="volume-label">成员音量 <span>{Math.round((volumes[member.id]??1)*100)}%</span><input aria-label="成员音量" type="range" min="0" max="1" step="0.01" value={volumes[member.id]??1} onChange={e=>{const v=Number(e.target.value);setVolumes({...volumes,[member.id]:v});voice.current?.volume(member.id,v);}}/></label><div className="member-actions"><button className="secondary" onClick={()=>{setScope('private');setMobile('chat');}}>私聊</button><button className="secondary" onClick={()=>{const text=prompt('戳一戳留言','你好！');if(text!==null)command('poke',{client:member.id,text});}}>戳一戳</button><button className="secondary" onClick={()=>{voice.current?.send({type:'whisper',clients:[member.id],channels:[]});setNotice(`已设置向 ${member.name} 耳语；在语音设置中可恢复频道发言。`);}}>耳语</button><button className="secondary" onClick={()=>setModal('member_manage')}>管理成员</button></div></>:<div className="empty-profile"><span className="avatar large"><Icon name="users"/></span><h3>认识频道里的伙伴</h3><p>选择一位成员，查看身份、<br/>调整音量或发起私聊。</p></div>}<div className="security-card"><Icon name="shield"/><strong>{connected?(cipher?'传输已加密':'等待加密确认'):'声音值得被保护'}</strong><p>浏览器 ↔ 网关<br/><span>{cipher||'AES-GCM · 协商后显示'}</span></p><p>网关 ↔ TeamSpeak<br/><span>AES-128-EAX · 强制加密</span></p><small>两段链路分别加密，网关能够接触语音内容。身份私钥由服务端加密托管。</small></div><a className="repo-link" href="https://github.com/PTPHAP/WebTS" target="_blank" rel="noreferrer">WebTS · 开源与社区 ↗</a></aside>
    </main>
    {modal==='auth'&&<Modal title={authResult?(authResult.success?(authResult.kind==='verify'?'邮箱验证完成':authResult.kind==='reset'?'密码已更新':'请查收邮件'):'暂时无法完成'):({login:'欢迎回来',register:'创建你的账号',forgot:'找回账号密码',verify:'确认你的邮箱',reset:'设置新密码',resend:'重新发送验证邮件'} as Record<string,string>)[auth]} close={()=>{setModal('');setAuthResult(null);}}>
      <div className="auth-brand"><span className="brand-mark"><Icon name="wave"/></span><span>一个账号，带上你的所有身份。</span></div>
      {authResult?<div className="auth-result" role="status">
        <div className={`auth-emblem ${authResult.success?'':'failed'}`}><Icon name={authResult.success?'shield':'close'}/></div>
        <p>{authResult.message}</p>
        {authResult.success&&['register','forgot','resend'].includes(authResult.kind)&&<><div className="auth-mailbox">{authEmail}</div><div className="auth-help">链接有效期为 15 分钟。没有收到？检查垃圾邮件，或稍后重新发送。</div></>}
        {authResult.success&&['verify','reset'].includes(authResult.kind)?<><div className="auth-help">{authResult.kind==='verify'?'现在可以登录，并创建或导入你的 TeamSpeak 身份。':'旧设备已退出登录；绑定的 TeamSpeak 身份仍然保留。'}</div><button className="primary full" onClick={()=>authView('login')}>前往登录 <Icon name="arrow"/></button></>:<><button className="primary full" onClick={()=>authView(authResult.kind==='forgot'||authResult.kind==='reset'?'forgot':'resend')}>重新发送{authResult.kind==='forgot'||authResult.kind==='reset'?'找回链接':'验证邮件'}</button><button className="text-button full" onClick={()=>authView('login')}>返回登录</button></>}
      </div>:<>
        {auth==='verify'?<><div className="auth-emblem"><Icon name="shield"/></div><p className="auth-intro">确认这个邮箱属于你。完成后，你就能登录 WebTS，让熟悉的频道与伙伴回到身边。</p><div className="auth-help">点击下方按钮完成验证。链接仅可使用一次，有效期为 15 分钟。</div></>:<p className="muted">{auth==='login'?'登录后，继续使用你绑定的 TeamSpeak 身份。':auth==='reset'?'设置新密码后，所有旧登录与语音连接将断开，绑定身份会保留。':auth==='resend'?'输入注册邮箱。我们会为尚未验证的账号发送一封新邮件。':'验证邮件和找回链接只会发送至你的注册邮箱。'}</p>}
        <form onSubmit={authenticate}>{authError&&<p className="auth-error" role="alert">{authError}</p>}
          {!['verify','reset'].includes(auth)&&<label>邮箱<input type="email" name="email" required autoComplete="email" defaultValue={authEmail} placeholder="you@example.com"/></label>}
          {!['forgot','verify','resend'].includes(auth)&&<label>{auth==='reset'?'新密码':'密码'}<input type="password" name="password" required minLength={auth==='login'?1:12} maxLength={128} autoComplete={auth==='login'?'current-password':'new-password'} placeholder="至少12个字符，建议使用长密码"/></label>}
          {auth==='reset'&&<label>确认新密码<input type="password" name="confirm" required minLength={12} maxLength={128} autoComplete="new-password" placeholder="再输入一次新密码"/></label>}
          {auth==='login'&&<label className="checkbox"><input name="remember" type="checkbox"/>记住登录，最长30天</label>}
          <button className="primary full" disabled={busy}>{busy?'处理中…':({login:'登录',register:'发送验证邮件',forgot:'发送找回链接',verify:'确认验证邮箱',reset:'重置密码',resend:'重新发送'} as Record<string,string>)[auth]}{!busy&&<Icon name="arrow"/>}</button>
        </form>
        <div className="auth-links"><button className="text-button" onClick={()=>authView(auth==='login'?'register':'login')}>{auth==='login'?'注册账号':'返回登录'}</button><button className="text-button" onClick={()=>authView(auth==='verify'?'resend':'forgot')}>{auth==='verify'?'链接过期？重新发送':'忘记密码？'}</button></div>
      </>}
      <div className="auth-footer"><Icon name="lock"/><span>身份独立于账号密码，重置密码后仍会保留。</span></div>
    </Modal>}
    {modal==='connect'&&<Modal title="连接你的声音空间" close={()=>setModal('')}><form onSubmit={connection}>{server==='$custom'&&<label>自定义公网地址<input value={customAddress} onChange={e=>setCustomAddress(e.target.value)} placeholder="ts.example.com:9987" maxLength={253} required/><small>填写公网域名或 IP，可带 UDP 端口，默认9987。不允许内网或回环地址。</small></label>}<label>显示昵称<input name="name" defaultValue={defaultNickname} minLength={3} maxLength={30} required/><small>昵称需3–30个字符，独立于身份名称，可在连接前修改。</small></label><label>服务器密码<input name="password" type="password" maxLength={256} placeholder="无密码时留空" autoComplete="off"/></label><label className="checkbox"><input name="listen" type="checkbox"/>仅收听，不打开麦克风</label><p className="muted">服务器必须启用全局语音加密，当前频道需使用 Opus。浏览器会请求麦克风权限。</p><button className="primary full" disabled={busy}>连接<Icon name="arrow"/></button></form></Modal>}
    {modal==='identities'&&<Modal title="你的 TeamSpeak 身份" close={()=>setModal('')}><p className="muted">每个身份拥有独立的 TS 权限。私钥由网站加密保存，网站服务具有解密能力。</p><div className="identity-list">{identities.map(i=><article className="identity-card" key={i.id}><header><strong>{i.name}</strong>{i.is_default&&<span className="tag">默认</span>}</header><code>{i.uid}</code><div><button className="text-button" onClick={()=>perform(async()=>{await api(`/identities/${i.id}`,{name:i.name,is_default:true},'PATCH');await refresh();})}>设为默认</button><button className="text-button" onClick={()=>{const name=prompt('新的身份名称',i.name);if(name)perform(async()=>{await api(`/identities/${i.id}`,{name,is_default:i.is_default},'PATCH');await refresh();});}}>重命名</button><button className="text-button" onClick={()=>exportIdentity(i)}>导出</button><button className="text-button danger" onClick={()=>{if(!confirm(`删除「${i.name}」？请先导出备份，删除后无法恢复。`))return;const password=prompt('请输入当前账号密码');if(password!==null)perform(async()=>{await api(`/identities/${i.id}/delete`,{password});await refresh();});}}>删除</button></div></article>)}</div><form onSubmit={e=>{e.preventDefault();const form=e.currentTarget;const name=String(new FormData(form).get('name'));perform(async()=>{await api('/identities',{name});await refresh();form.reset();});}}><label>新身份名称<input name="name" placeholder="例如：游戏 / 工作" maxLength={80} required/></label><div className="split-actions"><button className="primary" disabled={busy}><Icon name="plus"/>创建身份</button><label className="secondary file-button">导入身份文件<input type="file" accept=".ini,.txt" onChange={e=>{const file=e.target.files?.[0];if(!file)return;if(file.size>16384){setNotice('身份文件不能超过16KB');return;}const name=prompt('身份名称',file.name.replace(/\.[^.]+$/,''));if(name)perform(async()=>{await api('/identities/import',{name,identity:await file.text()});await refresh();});e.target.value='';}}/></label></div></form><small className="muted">导出文件包含私钥，请妥善保管。TS3可通过身份管理导入；TS6兼容情况见仓库使用文档。</small></Modal>}
    {modal==='account'&&<Modal title="账号与设备" close={()=>setModal('')}><p>{user?.email}</p><button className="secondary full" onClick={()=>{setAuth('forgot');setModal('auth');}}>通过邮箱重置密码</button><div className="split-actions"><button className="secondary" onClick={()=>perform(async()=>{await api('/auth/logout',{});disconnect();setUser(null);setIdentities([]);setServers([]);setModal('');})}>退出当前设备</button><button className="secondary danger" onClick={()=>perform(async()=>{await api('/auth/logout-all',{});disconnect();setUser(null);setIdentities([]);setServers([]);setModal('');})}>退出全部设备</button></div></Modal>}
    {modal==='admin'&&user?.is_admin&&<Modal title="站点管理" close={()=>setModal('')}><AdminSettings onSaved={refreshServers}/></Modal>}
    {modal==='audio'&&<Modal title="语音与设备" close={()=>setModal('')}><label>发言方式<select value={mode} onChange={e=>{const value=e.target.value as 'ptt'|'open';setMode(value);voice.current?.setMode(value);}}><option value="open">自由发言 · 持续开麦（默认）</option><option value="ptt">按键发言 · 空格 / 按住按钮</option></select></label><small className="muted">自由发言不使用音量阈值，静音后停止发送。按键发言仅在网页获得焦点时可用。仅收听连接不采集麦克风；连接时选择。</small><label>麦克风<select value={input} disabled={connected} onChange={e=>setInput(e.target.value)}><option value="">系统默认</option>{devices.filter(d=>d.kind==='audioinput').map((d,i)=><option key={d.deviceId||i} value={d.deviceId}>{d.label||`麦克风 ${i+1}`}</option>)}</select></label><small className="muted">切换麦克风后重新连接；授权后可显示设备名称。</small><label>收听设备<select value={output} onChange={e=>{setOutput(e.target.value);voice.current?.output(e.target.value).catch(()=>setNotice('当前浏览器不支持选择此输出设备，请使用系统音频设置。'));}}><option value="">系统默认</option>{devices.filter(d=>d.kind==='audiooutput').map((d,i)=><option key={d.deviceId||i} value={d.deviceId}>{d.label||`扬声器 ${i+1}`}</option>)}</select></label><div className="meter" aria-label="麦克风电平"><span style={{width:`${level*100}%`}}/></div><div className="split-actions"><button className="secondary" onClick={()=>voice.current?.resume()}>启用收听</button><button className="secondary" onClick={()=>{voice.current?.send({type:'whisper',clients:[],channels:[]});setNotice('已恢复频道发言。');}}>结束耳语</button></div>{connected&&<button className="secondary full" onClick={()=>{voice.current?.send({type:'whisper',clients:[],channels:own?[own.channel]:[]});setNotice('已设置向当前频道耳语。');}}>向当前频道耳语</button>}</Modal>}
    {['channel_create','channel_edit'].includes(modal)&&<Modal title={modal==='channel_create'?'创建频道':'编辑当前频道'} close={()=>setModal('')}><form onSubmit={e=>{e.preventDefault();const data=new FormData(e.currentTarget);const payload:Record<string,unknown>={name:data.get('name'),description:data.get('description')};if(modal==='channel_create'||data.get('changePassword')==='on')payload.password=data.get('password');payload.channel=channel?.id;payload.parent=Number(data.get('parent'));command(modal,payload,()=>setNotice('频道操作已完成'));setModal('');}}><label>名称<input name="name" defaultValue={modal==='channel_edit'?channel?.name:''} required maxLength={80}/></label>{modal==='channel_create'&&<label>父频道<select name="parent"><option value="0">顶层频道</option>{state?.channels.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label>}<label>描述<textarea name="description" defaultValue={modal==='channel_edit'?channel?.description:''} maxLength={4096}/></label>{modal==='channel_edit'&&<label className="checkbox"><input type="checkbox" name="changePassword"/>修改密码（留空表示移除密码）</label>}<label>频道密码<input name="password" type="password" autoComplete="off" maxLength={256}/></label><p className="muted">服务器根据当前身份权限执行操作，创建的频道使用 Opus。</p><button className="primary full">保存频道</button></form></Modal>}
    {modal==='member_manage'&&member&&<Modal title={`管理 ${member.name}`} close={()=>setModal('')}><p className="muted">所有操作均由 TeamSpeak 验证当前身份权限。</p><label>移动到频道<select defaultValue="" onChange={e=>{const target=state?.channels.find(c=>c.id===Number(e.target.value));if(!target)return;const password=target.password?prompt('目标频道密码'):'';if(password!==null)command('move',{client:member.id,channel:target.id,password});}}><option value="" disabled>选择频道</option>{state?.channels.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label><div className="split-actions">{['channel','server'].map(scope=><button key={scope} className="secondary danger" onClick={()=>{const text=prompt(`从${scope==='channel'?'频道':'服务器'}踢出 ${member.name} 的理由`,'');if(text!==null)command('kick',{scope,client:member.id,text});}}>{scope==='channel'?'踢出频道':'踢出服务器'}</button>)}</div><label>删除空频道<select defaultValue="" onChange={e=>{const channel=Number(e.target.value);if(confirm('确认删除此空频道？'))command('channel_delete',{channel});}}><option value="" disabled>选择要删除的空频道</option>{state?.channels.filter(c=>!state.members.some(m=>m.channel===c.id)).map(c=><option value={c.id} key={c.id}>{c.name}</option>)}</select></label></Modal>}
  </div>;
}
createRoot(document.getElementById('root')!).render(<App/>);
