import {useEffect,useRef,useState} from 'react';
import type {FormEvent} from 'react';
import {api} from './api';
import {ImageCropper} from './ImageCropper';
export type Announcement={id:string;title:string;text:string;image:string;enabled:boolean};
export type Home={site_name:string;site_icon:string;footer_html:string;operator:string;contact:string;data_details:string;privacy_policy:string;terms:string;title:string;subtitle:string;image:string;announcements:Announcement[]};
export const defaultHome:Home={site_name:'WebTS',site_icon:'',footer_html:'',operator:'',contact:'',data_details:'',privacy_policy:'',terms:'',title:'让声音，跨越距离。',subtitle:'与你熟悉的人，在熟悉的频道相聚。打开浏览器，让 TeamSpeak 随时在身边。',image:'',announcements:[]};
export function SiteHome({home,loggedIn,connected,enter,register}:{home:Home;loggedIn:boolean;connected:boolean;enter:()=>void;register:()=>void}){
  return <main className="site-home">
    <section className="site-hero"><div className="hero-copy"><span className="eyebrow"><i/> {home.site_name} · 声音连接你我</span><h1>{home.title}</h1><p>{home.subtitle}</p><div className="hero-actions"><button className="primary" onClick={enter}>{loggedIn?'进入语音空间':'登录，开始相聚'} <span aria-hidden="true">↗</span></button>{!loggedIn&&<button className="secondary" onClick={register}>创建账号</button>}</div><small>{connected?'你的语音连接仍在进行，点击进入即可返回。':'真实 TS 身份 · 原有频道与权限 · 本地 AI 降噪'}</small></div><div className="hero-art">{home.image?<img src={home.image} alt="站点展示图片"/>:<><div className="sound-orbit orbit-one"/><div className="sound-orbit orbit-two"/><div className="sound-core" aria-hidden="true">{[26,48,75,104,68,44,26].map((height,i)=><span key={i} style={{height}}/>)}</div><div className="floating-card card-top"><i/> 连接，从一句你好开始</div><div className="floating-card card-bottom">与你的频道，始终同频 <span>✦</span></div></>}</div></section>
    <div className="home-features"><article><span>01 / IDENTITY</span><h3>你还是熟悉的你</h3><p>导入客户端身份，保留 UID 和服务器权限。昵称、介绍与头像随账号保存。</p></article><article><span>02 / VOICE</span><h3>每一句，都清晰</h3><p>本地 AI 降噪、自由发言与按键发言。AFK、耳语和聊天在浏览器中完成。</p></article><article><span>03 / CONNECTION</span><h3>打开，就能相聚</h3><p>无需安装客户端。断线自动重连并恢复频道，手机界面也能从容使用。</p></article></div>
    <section className="site-announcements"><div className="section-title"><div><span className="eyebrow">COMMUNITY NOTES</span><h2>这里的新消息</h2></div><span>站点公告</span></div>{home.announcements.length?<div className="announcement-grid">{home.announcements.map(row=><article className="announcement-card" key={row.id}>{row.image&&<img src={row.image} alt="公告配图" loading="lazy"/>}<div><h3>{row.title}</h3><p>{row.text}</p></div></article>)}</div>:<div className="announcement-empty"><span>✦</span><p>相聚不需要理由。<small>站长发布的公告和活动将在这里展示。</small></p></div>}</section>

  </main>;
}
export function AdminHome({onSaved}:{onSaved:(home:Home)=>void}){
  const[home,setHome]=useState<Home|null>(null),[password,setPassword]=useState(''),[busy,setBusy]=useState(false),[cropFile,setCropFile]=useState<{file:File;id?:string;icon?:boolean}|null>(null),[message,setMessage]=useState('');const mounted=useRef(true);
  useEffect(()=>{mounted.current=true;api<Home>('/admin/home').then(v=>{if(mounted.current)setHome(v);}).catch(e=>{if(mounted.current)setMessage(e.message);});return()=>{mounted.current=false;};},[]);
  async function save(e:FormEvent){e.preventDefault();setBusy(true);try{const data=await api<Home>('/admin/home',{password,home});if(mounted.current){setHome(data);setMessage('外观、协议和首页已发布，刷新后即可查看；页脚已按安全规则过滤。');onSaved(data);}}catch(e){if(mounted.current)setMessage(e instanceof Error?e.message:'保存失败');}finally{if(mounted.current){setBusy(false);setPassword('');}}}
  if(!home)return <p role="status">{message||'正在读取首页…'}</p>;
  function row(id:string,change:Partial<Announcement>){setHome(h=>h&&({...h,announcements:h.announcements.map(r=>r.id===id?{...r,...change}:r)}));}
  const picker=(id?:string,icon=false)=><label>上传图片<input type="file" accept="image/png,image/jpeg,image/webp" onChange={e=>{const file=e.target.files?.[0];e.target.value='';if(file){setMessage('');setCropFile({file,id,icon});}}}/></label>;
  return <form className="admin-home" onSubmit={save}><p className="muted">首页对外公开。图片自动压缩并去除元数据；公告使用纯文本，不支持 HTML 或脚本。</p>{message&&<p role="status" className="auth-help">{message}</p>}<fieldset disabled={busy||!!cropFile}><legend>站点外观</legend><label>站点名称<input value={home.site_name} maxLength={40} required onChange={e=>setHome({...home,site_name:e.target.value})}/></label><label>站点图标</label>{home.site_icon&&<img className="site-icon-preview" src={home.site_icon} alt="站点图标预览"/>}{picker(undefined,true)}<small>图标沿用正方形裁剪，保存为 PNG，最多64KiB；同时用于页签图标。</small><button type="button" className="text-button" onClick={()=>setHome({...home,site_icon:''})}>恢复默认图标</button><h3>首页展示</h3><label>主标题<input value={home.title} maxLength={80} required onChange={e=>setHome({...home,title:e.target.value})}/></label><label>介绍<textarea value={home.subtitle} maxLength={300} onChange={e=>setHome({...home,subtitle:e.target.value})}/></label>{home.image&&<><img className="content-preview" src={home.image} alt="首页图片预览"/><button type="button" className="text-button" onClick={()=>setHome({...home,image:''})}>恢复默认图形</button></>}{picker()}<small>PNG / JPEG / WebP 最大4MiB；最多6条公告，图片总量约512KiB。</small>
    {home.announcements.map(item=><article className="identity-card" key={item.id}><label>公告标题<input value={item.title} maxLength={100} required onChange={e=>row(item.id,{title:e.target.value})}/></label><label>正文<textarea value={item.text} maxLength={2000} rows={4} onChange={e=>row(item.id,{text:e.target.value})}/></label><label className="checkbox"><input type="checkbox" checked={item.enabled} onChange={e=>row(item.id,{enabled:e.target.checked})}/>公开展示</label>{item.image&&<><img className="content-preview" src={item.image} alt="公告配图预览"/><button type="button" className="text-button" onClick={()=>row(item.id,{image:''})}>移除配图</button></>}{picker(item.id)}<button type="button" className="text-button danger" onClick={()=>setHome({...home,announcements:home.announcements.filter(r=>r.id!==item.id)})}>删除公告</button></article>)}
    <button type="button" className="secondary full" disabled={home.announcements.length>=6} onClick={()=>setHome({...home,announcements:[...home.announcements,{id:crypto.randomUUID(),title:'',text:'',image:'',enabled:true}]})}>添加公告</button><fieldset><legend>站点协议与页脚</legend><p className="muted">这些内容公开展示，请勿填写密码、授权码或身份资料。隐私政策需与实际运营方式一致。</p><label>运营者名称<input value={home.operator} maxLength={100} onChange={e=>setHome({...home,operator:e.target.value})}/></label><label>隐私联系与注销申请渠道<input value={home.contact} maxLength={200} placeholder="公开的邮箱或联系说明" onChange={e=>setHome({...home,contact:e.target.value})}/></label><label>实际部署与数据处理说明<textarea value={home.data_details} maxLength={4000} rows={4} placeholder="部署地区、主机/SMTP/TURN等接收方、日志与备份期限、申请流程" onChange={e=>setHome({...home,data_details:e.target.value})}/></label><label>隐私政策<textarea value={home.privacy_policy} maxLength={65536} rows={8} onChange={e=>setHome({...home,privacy_policy:e.target.value})}/></label><label>使用协议与免责声明<textarea value={home.terms} maxLength={65536} rows={8} onChange={e=>setHome({...home,terms:e.target.value})}/></label><label>页脚 HTML<textarea value={home.footer_html} maxLength={16384} rows={5} placeholder={'<p>友情链接：<a href="https://example.com">示例站点</a></p>\n<p><a href="https://beian.miit.gov.cn/">你的备案号</a></p>'} onChange={e=>setHome({...home,footer_html:e.target.value})}/></label><small>支持 HTTPS 链接、段落、列表、换行和基础文字格式。脚本、样式、图片、表单和 iframe 将过滤；保存后返回实际保留的 HTML。备案号需自行填写真实信息。</small></fieldset><label>验证当前管理员密码<input type="password" value={password} required maxLength={128} autoComplete="current-password" onChange={e=>setPassword(e.target.value)}/></label><button className="primary full" disabled={busy||!!cropFile}>{cropFile?'正在裁剪图片…':busy?'正在发布…':'保存并发布首页'}</button></fieldset>{cropFile&&<ImageCropper file={cropFile.file} purpose={cropFile.icon?'avatar':'content'} onCancel={()=>setCropFile(null)} onComplete={image=>{const id=cropFile.id;const icon=cropFile.icon;setHome(h=>h&&(icon?{...h,site_icon:`data:image/png;base64,${image}`}:id?{...h,announcements:h.announcements.map(r=>r.id===id?{...r,image}:r)}:{...h,image}));setCropFile(null);}}/>}</form>;
}
